- _config.yml
This was one last config we needed to set up TravisCI and have tests run against our PRs!
> Set up repo with TravisCI

- _data/help.yml
added authenticator app definition to help page
> added authenticator app definition

- _includes/nav.html
> Update link to developers site

- _data/policy.yml
> Small tweaks to the page

- _pages/index.md
> Update static site homepage

- _data/policy.yml
- _pages/contact.md
- _pages/index.md
- spec/_pages/index.md_spec.rb
Updates contact email address and adds spec for New Relic checks
> Deploy to Production

- _pages/contact.md
> updated contact page

- _pages/index.md
> small tweak on column header

- _includes/meta.html
> Fix meta image URL

- _i18n/en.yml
I have my editor set to highlight these and I figured I'd clean them up
> Remove trailing whitespace

- _pages/developers.md
**Why** @jeanninehunter and I have notes from our critique group to help improve the page.
> Adding in changes from crit session

- _pages/developers.md
- spec/_pages/developers.md_spec.rb
> Small /developers copy changes for clarity

- _i18n/en.yml
- _includes/nav.html
- _pages/developers.md
Move content of developers page into i18n strings.
> Add developer page translation strings

- _pages/developers.md
Small fix to point contact link to contact page instead of directly to email address.
> Update developers contact link

- README.md
- _i18n/en.yml
This moves a couple of links to HTTPS, and adds an install instruction to the README.
> Fix a couple links

- _i18n/en.yml
Separate the words `Built cooperatively` on mobile.
> Add space before responsive line break

- .gitignore
> Update .gitignore for .DS_Store files

- _i18n/en.yml
> Add missing apostrophes to help pages

- _i18n/es.yml
> Add missing spanish translations

- _config.yml
- _help/index.md
- _i18n/en.yml
- _i18n/es.yml
- _includes/footer.html
- _includes/help/nav_page_top.html
- _includes/help/nav_page_top_small.html
- _includes/meta.html
- _pages/404.html
- _pages/contact.md
- _pages/developers.md
- _pages/index.md
- _pages/playbook/implementation.md
- _pages/playbook/index.md
- _pages/playbook/principles.md
- _pages/policy.md
- _pages/security.md
Allow page titles and descriptions to be translated.
> Translate page titles and descriptions

- _i18n/en.yml
- _i18n/es.yml
- _i18n/es/help/creating-an-account/how-do-i-create-an-account-with-logingov.md
- _pages/index.md
**Why**: Help improve the site
> Add copy changes from QA feedback for Spanish

- _i18n/en.yml
- _i18n/es.yml
- _pages/index.md
edited copy under the hero image; still need new illustration atop middle column.
> edited copy under the hero image

- _i18n/en.yml
- _i18n/es.yml
Replaced Jan one w/ one from August
> Hunter new sorn

- _i18n/en.yml
- _pages/contact.md
Adds additional contact options and content to the contact page.
**Before:**
**After:**
> Update contact page content

- _config.yml
- _i18n/es.yml
- _includes/i18n_dropdown_desktop.html
- _includes/i18n_dropdown_mobile.html
Enable Spanish in the config since it is now live in production. This also updates several strings that were recently translated.
Wait to merge until [English contact page PR](https://github.com/18F/identity-site/pull/146) has been merged.
> Enable Spanish and update latest translations

- _i18n/fr.yml
**Why**: So the static site can be made available in French
@zachmargolis: I made sure they're in French this time 😳
> Add missing french translations

- _i18n/en.yml
Small error in: https://github.com/18F/identity-site/pull/164/files
> Fix markdown link syntax

- _i18n/en.yml
**Why**: Contact center is back
> Remove contact center advisory

- spec/_pages/contact.md_spec.rb
- spec/_pages/developers.md_spec.rb
- spec/_pages/help.md_spec.rb
- spec/_pages/index.md_spec.rb
- spec/_pages/playbook_spec.rb
- spec/_pages/policy.md_spec.rb
- spec/_pages/security.md_spec.rb
- spec/support/matchers.rb
**Why**: Would have caught Markdown typo: #169
> Add specs to ensure valid links

- _i18n/en.yml
**Why**:
Number was removed due to call volume.
Added additional clarifcation to TTP
> Update contact page to address issues with ttp

- _help/index.md
- _help/trusted-traveler-programs/another-question.md
- _help/trusted-traveler-programs/aol-verizon.md
- _help/trusted-traveler-programs/application-status.md
- _help/trusted-traveler-programs/do-i-need-to-pay-again.md
- _help/trusted-traveler-programs/dont-know-passid.md
- _help/trusted-traveler-programs/family-account.md
- _help/trusted-traveler-programs/known-traveler-number.md
- _help/trusted-traveler-programs/no-text-message.md
- _help/trusted-traveler-programs/schedule-an-appointment.md
- _help/trusted-traveler-programs/sign-in-doesnt-work.md
- _help/trusted-traveler-programs/whats-going-on.md
- _i18n/en.yml
- _i18n/es.yml
- _i18n/fr.yml
**Why**:
More questions for TTP users
> Add additional FAQ TTP Questions

- _config.yml
- _help/index.md
- _help/usajobs/gov-mil-edu-email-address.md
- _help/usajobs/profile-information.md
- _help/usajobs/security-code.md
- _help/usajobs/what-email-address-do-i-use.md
- _help/usajobs/what-happens-to-my-profile.md
- _i18n/en.yml
**Why**: We need to add a FAQ to Help Center to support the USAJobs rollout
**How** Modified drop down menus, menubar, and added new pages
> Add USAJobs FAQ to Help Center

- _i18n/en.yml
**Why**: It will provide easier ways to contact us.
**How** Changed text in yml file
> Update contact page to include phone number and email addresses

- _help/usajobs/profile-information.md
**Why**:
We want "what if i don't see my
profile" to be the second topic
> Reorder USAJOBS help topics

- _i18n/en.yml
Emphasizing our support info at the top
> Clarify contact info

- _i18n/en.yml
- package-lock.json
- package.json
Changes from 18F/ah-contact to add spacing and (hopefully) make the UL render correctly
> Fix (hopefully) for broken UL

- package-lock.json
- package.json
In prior commit, I believe package changes were inadvertently added. 
I've run `npm update` and re-committed.
> Fix inadvertent package changes

- _i18n/en.yml
> Update contact info

- _i18n/en.yml
Clarifies security of personal information
> Deploy to prod

- _i18n/en.yml
> Help Center Content Updates

- _i18n/en.yml
- _i18n/es.yml
- _i18n/fr.yml
**Why**: Doing this will make the diffs easier to review when we start
adding translations programmatically
All of the translations themselves should be the same now.
> Sort and normalize translation files

- _i18n/en.yml
- _i18n/es.yml
- _i18n/fr.yml
- spec/i18n_spec.rb
- spec/support/missing_translation_finder.rb
**Why**: So that the site will be fully available in French and Spanish.
This commit also adds a test that will fail if translations are missing.
> LG-513 Translate remaining strings

- _i18n/en.yml
- _i18n/es.yml
- _i18n/fr.yml
- _includes/contact_form.html
Adds default unselected states to form fields on the contact form.
Still needs translation.
> Add default unselected states to form fields

- _includes/contact_form.html
the label and input ID don't match up with the name of the input so data is being sent to the wrong place
> update input name for phone field

- _i18n/en.yml
- _i18n/es.yml
- _i18n/fr.yml
- _includes/contact_form.html
**Why**: Because @clantosswett asked me to.
> Remove EOP Hipchat from SP list

- _i18n/en.yml
- _i18n/es.yml
- _i18n/fr.yml
- yarn.lock
We now say IAL1 and IAL2 when appropriate and changed content to reflect our 800-63-3 compliance.
> LG-1052 Update the references to 800-63-2 and LOA1 and LOA3

- _i18n/es.yml
updating the verify by mail FAQ spanish translation to reflect changes in english
> Updating FAQ verify by mail content in spanish

- _i18n/fr.yml
Updating the verify by mail FAQ French translation to reflect changes to the English
> Updating FAQ verify by mail content in french

- _i18n/en.yml
- _i18n/es.yml
- _i18n/fr.yml
- _includes/contact_form.html
June update received from Contact Center/SF team with all new topics and subtopics as well as the correct SPs to show in the Agency dropdown.
> LG-1961 - Changes to the list of SPs, topics, and subtopics

- _i18n/en.yml
- _i18n/es.yml
- _i18n/fr.yml
- _includes/contact_form.html
> LG-1998 Contact form updates on the agency list

- _i18n/en.yml
- _i18n/es.yml
- _i18n/fr.yml
- _includes/contact_form.html
not sure if the agency request form needs to be fixed too @cpbgsa
> fix FMCSA typo

- _includes/contact_form.html
SF changed the misspelled value so we're fixing it in the form.
> LG-2036 Change FCMSA to FMSCA

- _includes/contact_form.html
Why: Add honey pot to contact us form to reduce spam messages received by our support team.
> Better honneypot for contact us

- _includes/contact_form.html
- _includes/google_recaptcha.html
- _layouts/main.html
- _sass/components/_recaptcha.scss
- _sass/components/all.scss
WHY -
As a contact center person, I want a mechanism for stopping spammy support requests, so that my queue is not flooded with spam support requests
> LG-2398_add_recaptcha

- _includes/contact_form.html
Feedback from the contact center team
> Update recaptcha site key

- _config.yml
- _includes/hubbot.html
- _layouts/main.html
- _layouts/partners.html
- package-lock.json
**Why**
So automated bot can respond to recurring simple questions about Partnership
> Lg 2440 - Automated response for partner questions

- _i18n/en.yml
- _includes/contact_form.html
Adds new dropdown options, fixed a typo
> LG-2349: Update contact form

- spec/sitemap.xml_spec.rb
> Add spec for sitemap.xml

- _i18n/en.yml
- _i18n/es.yml
- _i18n/fr.yml
I took a guess at making some of the Spanish sentences less redundant, but am not sure about French, so just did an in-place copy
> LG-2789: update FAQs to use reference updated "sign in" copy

- _i18n/en.yml
- _i18n/es.yml
- _i18n/fr.yml
- package-lock.json
**WHY** TTP has updated some of their URLs. We are updating our documentation with the new links
> Lg 2864 Updates to links for trusted traveler program

- _includes/banner.html
- _pages/index.md
WHY 
So an agency with an urgent need related to COVID-19 response efforts knows where to click
> Adding agency CTA covid 

- _i18n/en.yml
- _i18n/es.yml
- _i18n/fr.yml
- _includes/banner.html
- _sass/components/_header.scss
- yarn.lock
> Fixing the CTA placement in covid banner LG 2900

- _i18n/en.yml
- _i18n/es.yml
- _i18n/fr.yml
- _includes/contact_form.html
- _sass/components/_form.scss
**Why**: LG-2972
**Why**: So users can accurately specifiy the agency/application of concern
**How**: Updated form template and translations
> Added Veterans Affairs to contact form

- _i18n/en.yml
- _i18n/es.yml
- _i18n/fr.yml
- _includes/contact_form.html
**Why**: Salesforce has not yet deployed the corresponding changes
**How**: Update template and translations
> Revert addition of Veterans Affairs option

- _i18n/en.yml
- _i18n/es.yml
- _i18n/fr.yml
- _includes/contact_form.html
**Why**: Salesforce has deployed the corresponding changes
**How**: Updated template and translations
> Restored Veterans Affairs option to contact form

- _includes/banner.html
- _includes/header.html
- package-lock.json
**Why**: To improve UX
**How**: default hidden tags on header/submenus
> Removed flickering of header/submenus

- _includes/google_analytics.html
- assets/js/analytics.js
- assets/js/main.js
**Why**: So that the login.gov GA events are not reported to a cloud.gov property
> Remove unused GA properties

- _i18n/en.yml
- _i18n/es.yml
- _i18n/fr.yml
- _includes/contact_form.html
- package-lock.json
Main goal: Add DS Logon (LG-3074)
**Note**: We need to wait for confirmation from the backend team before deploying, I'll make sure not to merge until I get confirmation
While I was here, I did some cleanup:
1. I alphabetized the dropdown
2. I added groupings and floated the most common applications to the top
(the groupings don't affect the backend)
> Update contact form dropdown

- _i18n/en.yml
Thanks @bpdesigns for the catch!
(this was my bad! #364 😬 )
> Fix typo in FAQ

- _i18n/fr.yml
Capitalizing first letters of sentences
> Updating French homepage with first letter caps

- _i18n/en.yml
- _i18n/es.yml
- _i18n/fr.yml
- scripts/htmlproofer-external
- Link to `?language=es` in Spanish translations
> Update CBP help URL

- package-lock.json
- package.json
- webpack.config.js
- yarn.lock
**Why**: To use the latest and greatest (and make Snyk happy)
> Upgrade webpack to v4

- _i18n/en.yml
- _i18n/es.yml
- _i18n/fr.yml
- _includes/contact_form.html
This reverts commit fd66704e44ba63e62762a5434c9d0befbec09f53.
(this wasn't ready to go live yet)
> Revert "Add contact dropdown option for SBA Connect (LG-3220) (#421)"

- _i18n/en.yml
- _i18n/es.yml
- _i18n/fr.yml
- _includes/contact_form.html
(revert of a revert)
This reverts commit 98082cefcdb13035548bee0a280c8d14d5c0b152.
> Add SBA Connect to contact form (LG-3220)

- _i18n/en.yml
- _i18n/es.yml
- _i18n/fr.yml
**Why**: So users understand the importance of safeguarding (LG-3208)
> Update help content for loss of MFA devices

- _i18n/en.yml
- _i18n/es.yml
- _i18n/fr.yml
Created this branch then executed `git merge master`.
> Update demo with MFA updates from master

- _includes/footer.html
- _pages/index.md
- _sass/components/_footer.scss
- _sass/components/_nav.scss
- yarn.lock
* Renamed CSS classnames to avoid sense of fixed order
> * Moved pre-footer nav into footer

- _includes/banner.html
- _includes/footer.html
- _includes/header.html
- _includes/language_search.html
- _layouts/main.html
- _pages/index.md
- _sass/components/_layout.scss
- _sass/components/_nav.scss
- _sass/components/all.scss
**Why**: Flaws were clear at various resolutions
**How**: Container (CSS) classes
**How**: Swapped h6 class for small-text
**How**: Markup/attribute cleanup
**How**: Moved search within .container margin
> Make layout margins consistent

- _i18n/en.yml
- _i18n/es.yml
- _i18n/fr.yml
Per request from LG-3356 acceptance thread.
> Move bulleted links into last paragraph of policy intro

- _i18n/en.yml
- _i18n/es.yml
- _i18n/fr.yml
- _pages/policy/privacy.md
- Renames page, adds redirect
- Updates copy based on feedback from OGC
> Privacy page updates (LG-3467)

- _i18n/en.yml
* Fix the "your account page" link in the "What happens to the information you share?" section
> fix link on Our privacy act statement

- spec/_pages/contact.md_spec.rb
- spec/_pages/help.md_spec.rb
- spec/_pages/index.md_spec.rb
- spec/_pages/partners.md_spec.rb
- spec/_pages/playbook_spec.rb
- spec/_pages/policy.md_spec.rb
- spec/_pages/policy/index.md_spec.rb
- spec/_pages/security.md_spec.rb
- spec/support/matchers.rb
**Why**: We had been ignoring this in a bunch of places anyways
> Remove expectation that external links must open in a new window

- .circleci/config.yml
- .eslintignore
- .eslintrc
- .prettierrc.json
- README.md
- assets/js/main.js
- package-lock.json
- package.json
- webpack.config.js
**Why**: Use same configuration across `18f/identity-idp`, `18f/identity-style-guide`
> Use consistent Prettier configuration

- _config.yml
- _i18n/en.yml
- _i18n/es.yml
- _i18n/fr.yml
- _includes/footer.html
After our IRP testing yesterday it seemed like this would be useful - feedback welcome!
> Add link to status page in the footer

- .circleci/config.yml
- .gitignore
- Makefile
- Makefile.server
- _config.yml
- _plugins/style_guide_assets.rb
- assets/css/main.scss
- package-lock.json
- package.json
**Why**: Fewer mechanisms to maintain, reliance on existing documentation over undocumented custom approach, fewer dependencies to maintain, possibly faster compilations†.
† https://jekyllrb.com/news/2019/08/20/jekyll-4-0-0-released/#super-powered-content-transformations-
> Use Jekyll default assets management for SASS compilation

- package-lock.json
**Why**: Unblock new pull requests
> Bump dependencies using npm audit fix

- OLD_URLS.yml
- _config.yml
- _help/changing-settings/add-or-remove-email-address.md
- _help/changing-settings/change-my-email-address.md
- _help/changing-settings/change-my-password.md
- _help/changing-settings/change-my-phone-number.md
- _help/changing-settings/delete-my-account.md
- _help/changing-settings/email-address-is-already-in-use.md
- _help/changing-settings/get-a-new-personal-key.md
- _help/changing-settings/index.md
- _help/changing-settings/remove-saved-password-from-browser.md
- _help/changing-settings/turn-off-two-factor-authentication.md
- _help/trouble-signing-in/overview.md
- _i18n/en.yml
- _i18n/es.yml
- _i18n/fr.yml
- _layouts/help.html
- _sass/components/_list.scss
- _sass/components/_nav.scss
Trouble Signing In (5.2) Translations in Spanish(es) and French (fr).
**Soft launch will not include:**
**Translations directory**: https://drive.google.com/drive/folders/142tmHLXjVp5mtVZv51tTdUqe8vucKt9A
> Translate help Trouble Signing In page into Spanish and French.

- _config.yml
- _i18n/en.yml
- _i18n/es.yml
- _i18n/fr.yml
- _includes/contact_form.html
- _pages/contact.md
- _sass/components/_recaptcha.scss
- _sass/components/all.scss
- assets/js/contact.js
- webpack.config.js
**Why**: The current implementation poses usability and accessibility challenges by rendering a visible-but-offscreen, unlabelled textarea input. This allows the form to validate it as a required field using native form validation, but can be confusing to keyboard users and users of assistive technology, as it would not be clear to them the purpose of the textarea.
Related Slack discussion: https://gsa-tts.slack.com/archives/C01710KMYUB/p1608670099403700
> Validate captcha on form submission

- .circleci/config.yml
- README.md
I can also port these these changes to `demo` branch if we think that eventually they won't merge cleanly
> Update references to point to main branch (LG-3379)

- _config.yml
- _help/README.md
- _help/verify-your-identity/dont-have-a-state-issued-id.md
- _help/verify-your-identity/how-to-verify-your-identity.md
- _help/verify-your-identity/overview.md
- _help/verify-your-identity/personal-key-issues.md
- _help/verify-your-identity/verify-your-address-by-mail.md
- _i18n/en.yml
- _i18n/es.yml
- _i18n/fr.yml
- _pages/help.md
Adds overview page and stubs out the 4 articles (they're all blank for now)
| English | Spanish | French |
| --- | --- | --- |
| <img width="1295" alt="Screen Shot 2021-01-06 at 12 00 33 PM" src="https://user-images.githubusercontent.com/458784/103815436-385d2e00-5018-11eb-8701-07ce375b7ea0.png"> | <img width="1295" alt="Screen Shot 2021-01-06 at 12 00 41 PM" src="https://user-images.githubusercontent.com/458784/103815435-372c0100-5018-11eb-80eb-d924ed20c41e.png"> | <img width="1295" alt="Screen Shot 2021-01-06 at 12 07 45 PM" src="https://user-images.githubusercontent.com/458784/103815429-34c9a700-5018-11eb-88da-f6ab6f3058cb.png"> |
> Add "Verify your identity" help section (LG-3564)

- _help/README.md
- _help/specific-agencies/overview.md
- _help/specific-agencies/sam.md
- _help/specific-agencies/trusted-traveler-programs.md
- _help/specific-agencies/usajobs.md
- _i18n/en.yml
- _i18n/es.yml
- _i18n/fr.yml
- Just overview, TTP and SAM, we don't have USAJOBS yet
- Update pages to translate title, update _help/README.md to reflect this
> Add translations for agency help pages

- _i18n/en.yml
- _i18n/es.yml
- _i18n/fr.yml
See text changes in https://cm-jira.usa.gov/browse/LG-4000
> Update password guidelines text

- _layouts/help_landing.html
- _pages/help.md
Reverts 18F/identity-site#565
Precautionary revert based on suspected problems described in https://github.com/18F/identity-site/pull/565#issuecomment-764905815.
> Revert "Refactor help landing page as an html template,  not md."

- _help/manage-your-account/change-your-email-address.md
- _help/manage-your-account/change-your-phone-number.md
- _i18n/en.yml
- _i18n/es.yml
- _i18n/fr.yml
Content
5.3.3 Change the phone number associated with your account
Redirect:
5.3.4 Change the email address associated with your account
Spanish and French Translations attached
> Add change phone and change email pages

- _config.yml
- _i18n/en.yml
- _i18n/es.yml
- _i18n/fr.yml
- _includes/contact_form.html
- assets/js/contact.js
(the second commit is just so we can test against the sandbox before deploying. Maybe we can take advantage of federalist's per-branch configs so we don't have to remember to do these changes just to be able to test?
> Update contact form to add SSA (LG-4347)

- _includes/contact_form.html
Quick update: https://gsa-tts.slack.com/archives/C0184P9SCJ0/p1617812209076800?thread_ts=1617811424.076000&cid=C0184P9SCJ0
> Add SSA to commmon applications section as well

- _includes/components/2-col.html
- _layouts/main.html
- admin/config.yml
- content/_en/landing/create_an_account.md
- content/_en/landing/index.md
- content/_en/landing/what_is_login.md
- content/_en/landing/who_uses_login.md
- content/_es/landing/create_an_account.md
- content/_es/landing/index.md
- content/_es/landing/what_is_login.md
- content/_es/landing/who_uses_login.md
- content/_fr/landing/create_an_account.md
- content/_fr/landing/index.md
- content/_fr/landing/what_is_login.md
- content/_fr/landing/who_uses_login.md
AC:
...
Covers two tickets: LG-4240, LG-4186
> Add landing page configuration to Netlify CMS

- _includes/contact_form.html
The translations made it to the branch but the contact form options didn't, this fixes that
> Redo adding SSA to contact form dropdown

- _config.yml
- _data/en/settings.yml
- _data/es/settings.yml
- _includes/components/3-col.html
- _includes/meta.html
- _layouts/landing.html
- admin/config.yml
- content/_en/landing/index.md
- content/_es/landing/index.md
- content/_fr/landing/index.md
This PR adds a three column layout option for the landing pages
> Jd three column layout

- admin/config.yml
This PR resolves previously addressed bugs that were somehow overwritten.
> make permalink optional; remove order; add none to page type dropdown

- _includes/components/2-col.html
- _includes/components/3-col.html
- admin/config.yml
This branch has some quick fixes to Netlify CMS. Specifically:
- Make permalink required again. 
- Make Column 3 in the three column layout optional
This PR also removes the site url from the two and three column layouts
> Additional bug fixes for Netlify CMS

- admin/config.yml
- content/_es/help/manage-your-account/relink-your-accounts.md
- content/_es/landing/index.md
- content/_fr/help/manage-your-account/relink-your-accounts.md
Attempt to fix error in production with translations not appearing
> fix duplicate key error

- _data/en/settings.yml
- _data/es/settings.yml
- _data/fr/settings.yml
- _includes/components/who-uses-login.html
- _layouts/landing.html
- content/_en/landing/who_uses_login.md
- content/_es/landing/who_uses_login.md
- content/_fr/landing/who_uses_login.md
Previously, the content for the "Who uses login" page was unavailable to edit. This PR makes it so that the content is editable through NetlifyCMS.
> LG-4588: Convert "Who uses login" page to NetlifyCMS

- _includes/already_have_an_account_banner.html
This PR addresses a failed test in switching locales when a user switches page language
> make sure locale url is prepended

- _includes/google_analytics.html
- _includes/gtm_body.html
- _includes/gtm_head.html
- _layouts/base.html
This pull request adds an update of the GA tracking code, as well as GTM to our base.html template.
> Updating GA + GTM to login.gov

- _data/en/settings.yml
- _data/es/settings.yml
- _data/fr/settings.yml
- _includes/contact_form.html
This PR updates the Spanish and French translations on the Contact Us page.
> Contact us form changes

- content/_en/help/verify-your-identity/accepted-state-issued-identification.md
- content/_en/help/verify-your-identity/how-to-verify-your-identity.md
- content/_en/help/verify-your-identity/phone-number-and-phone-plan-in-your-name.md
- content/_en/help/verify-your-identity/verify-your-address-by-mail.md
- content/_es/help/verify-your-identity/accepted-state-issued-identification.md
- content/_es/help/verify-your-identity/how-to-verify-your-identity.md
- content/_es/help/verify-your-identity/phone-number-and-phone-plan-in-your-name.md
- content/_es/help/verify-your-identity/verify-your-address-by-mail.md
- content/_fr/help/verify-your-identity/accepted-state-issued-identification.md
- content/_fr/help/verify-your-identity/how-to-verify-your-identity.md
- content/_fr/help/verify-your-identity/phone-number-and-phone-plan-in-your-name.md
- content/_fr/help/verify-your-identity/verify-your-address-by-mail.md
This ticket adds the "Verify your address by mail" and "Phone number and phone plan in your name" pages to the help center.
> Implement "identity verification" help articles

- _layouts/landing.html
- admin/config.yml
- content/_en/landing/create_an_account.md
- content/_en/landing/index.md
- content/_en/landing/what_is_login.md
- content/_en/landing/who_uses_login.md
- content/_es/landing/create_an_account.md
- content/_es/landing/index.md
- content/_es/landing/what_is_login.md
- content/_es/landing/who_uses_login.md
- content/_fr/landing/create_an_account.md
- content/_fr/landing/index.md
- content/_fr/landing/what_is_login.md
- content/_fr/landing/who_uses_login.md
The purpose of this ticket is to change the hero image on the "Create an account" page
Why: To keep fidelity with Login.gov designs.
> LG-4619: Fix hero illustrations for the "Create an account" page

- content/_en/help/verify-your-identity/how-to-add-images-of-your-state-issued-id.md
- content/_es/help/verify-your-identity/how-to-add-images-of-your-state-issued-id.md
- content/_fr/help/verify-your-identity/how-to-add-images-of-your-state-issued-id.md
This ticket adds the "How to add images of your state-issued ID to the help pages
> LG-5076: Add troubleshooting content to Help Center

- _data/en/settings.yml
- _data/es/settings.yml
- _data/fr/settings.yml
- content/_en/policy/contact.md
- content/_es/policy/contact.md
- content/_fr/policy/contact.md
This PR adds "Report a Security or Privacy Issue" content to the footer of the Contact us page.
Notes:
- I see that the editor is adding additional and extra spacing in between paragraphs and bullets. This needs to be explored further by the technical team.
> Update footer with new "Report a Security or Privacy Issue" content

- content/_help/verify-your-identity/accepted-state-issued-identification._en.md
- content/_help/verify-your-identity/accepted-state-issued-identification._es.md
- content/_help/verify-your-identity/accepted-state-issued-identification._fr.md
The following pull request changes the text for accepted state issued identification to include dc.
> LG-5434-update text for accepted-state-issued-idenitifcation

- _includes/footer.html
- content/_policy/rules-of-use._en.md
- content/_policy/rules-of-use._es.md
- content/_policy/rules-of-use._fr.md
(do not merge while we wait for some HTTPS issues to get sorted out)
> Update status page links to point at new domain (LG-5512)

- _includes/header--help.html
Was leveraging the old way we formatted the collection
> LG-5575: fix subpage article

- .circleci/config.yml
- _data/en/settings.yml
- _data/es/settings.yml
- _data/fr/settings.yml
- _includes/contact_form.html
- content/_help/get-started/authentication-options._en.md
- content/_help/get-started/authentication-options._es.md
- content/_help/get-started/authentication-options._fr.md
- content/_help/manage-your-account/change-your-phone-number._en.md
- content/_help/manage-your-account/change-your-phone-number._es.md
- content/_policy/contact._en.md
- content/_policy/contact._es.md
- content/_policy/contact._fr.md
- scripts/htmlproofer
Update content for Contact us.
> LG-5475 implement content change

- _data/en/settings.yml
- _includes/partners/header.html
- _includes/partners/partners-banner.html
- content/_en/partners/faq.md
* Fix issue with broken href
* Fix MissingTranslation issue
> Fixing Partner site unit tests

- _layouts/partners/faq.html
- _layouts/partners/get-started.html
- _sass/components/partners/_partners.scss
- content/_en/partners/faq.md
- fixes font size of FAQ page title
- fixes background color of footer
- expand all / collapse all functionality specific to content sections
> Partners site redesign FAQ follow-ups

- content/_policy/rules-of-use._en.md
- content/_policy/rules-of-use._es.md
- content/_policy/rules-of-use._fr.md
I've included a spreadsheet containing the translations to the original ticket. Purpose of this PR is to update the Rules of Use.
Related timestamp update on IDP can be found here: https://github.com/18F/identity-idp/pull/5837
> Add updates to rules of use (LG-5520)

- content/_policy/how_does_it_work._en.md
- content/_policy/how_does_it_work._es.md
- content/_policy/how_does_it_work._fr.md
Clarifies conformance on the how it works pages
> Updates refs to spec

- _data/fr/settings.yml
Removes unused paragraph (p_5)
> Updates fr copy

- _config.yml
- _includes/partners/contact.html
- _layouts/partners/contact.html
- content/_en/partners/contact.md
- Created contact page per design document
- Embedded partners Hubspot form per ticket notes
> LG-5392 Added contact page with embedded form

- _includes/contact_form.html
This ticket makes it so that if a user selects "Feedback for Login.gov" or "Other" topic option, it will automatically select "Other" as the subtopic.
Why: [To address the bug that was brought up on Twitter](https://twitter.com/ebuie/status/1486444396920856585)
> Lg 5755 contact form dropdown

- _includes/contact_form.html
Reverts 18F/identity-site#813 to make sure that no changes need to be made in the Salesforce back end
> Revert "Lg 5755 contact form dropdown"

- _includes/partners/checklist.html
- content/_partners/faq.md
- content/_partners/index._en.md
Fix unit tests by adding trailing slashes to internal links
> Add slashes to internal links

- _includes/partners/contact.html
- _layouts/partners/faq.html
- _layouts/partners/get-started.html
- _layouts/partners/landing.html
- _layouts/partners/state-and-local.html
- content/_partners/faq.md
- content/_partners/our-services.md
- content/_partners/security-experience.md
Add tags to iFrames
Add unique IDs for repetitive headers
Fix header sizing
> Fix accessibility tests

- _includes/banner.html
- _includes/components/2-col.html
- _includes/footer.html
- _includes/header.html
- _includes/partners/header.html
- _includes/partners/x-col.html
Cleaning up accessibility tests. Swarming! 🐝
> Accessibility cleanup for partners redesign

- package-lock.json
- package.json
**Why**: To resolve an issue where the search field "Submit" button text is not visible at small viewport sizes.
Changelogs:
- https://github.com/18F/identity-style-guide/releases/tag/v6.4.0
- https://github.com/18F/identity-style-guide/releases/tag/v6.4.1
Live preview URL: https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.app.cloud.gov/preview/18f/identity-site/aduth-ds-6-4-1/
> Update design system to v6.4.1

- _includes/header.html
- _includes/partners/header.html
- _sass/components/_nav.scss
https://cm-jira.usa.gov/browse/LG-6150
Updated to look like attached:
> Fixes the red lines spacing below the partners navigation links.

- _layouts/partners/rrb-impact-story.html
- content/_partners/rrb-impact-story._en.md
Why?: Added a quote to the impact story for the railroad retirement board
> LG-6188 Enhance Impact Story

- _layouts/partners/get-started.html
- _layouts/partners/state-and-local.html
| ---- | --- |
| <img width="1188" alt="Screen Shot 2022-05-20 at 11 27 06 AM" src="https://user-images.githubusercontent.com/458784/169590869-1fd29bc1-54e1-4a0b-bcc1-ce9890546403.png"> | <img width="1188" alt="Screen Shot 2022-05-20 at 11 27 08 AM" src="https://user-images.githubusercontent.com/458784/169590898-c74162d3-21f7-4a89-9734-4ebf8a8d645a.png"> |
| <img width="1188" alt="Screen Shot 2022-05-20 at 11 27 39 AM" src="https://user-images.githubusercontent.com/458784/169590925-157773ff-dc89-45a3-82b1-bfaa4067f70a.png"> | <img width="1188" alt="Screen Shot 2022-05-20 at 11 27 27 AM" src="https://user-images.githubusercontent.com/458784/169590915-79102efc-c113-4adb-882a-2835332882a3.png"> |
> Use connected line class for IAA, IGCA lists (LG-6322)

- _includes/banner.html
Addresses https://github.com/18F/identity-site/pull/826#discussion_r880787900
> Add back role="img"

- content/_partners/our-services._en.md
- Add link to /policy page
- Update which text is hyperlinked for FedRAMP
|----| ---- |
| <img width="1158" alt="Screen Shot 2022-05-26 at 11 15 50 AM" src="https://user-images.githubusercontent.com/458784/170550890-5d22076b-b627-44bb-a3dd-7e82651537e8.png"> | <img width="1158" alt="Screen Shot 2022-05-26 at 11 15 53 AM" src="https://user-images.githubusercontent.com/458784/170550897-64171ceb-046e-4449-a9a8-28bdd4518b17.png"> |
> Fix links in "Benefits of partnering with Login.gov" section (LG-6326)

- content/_partners/get-started._en.md
- content/_partners/rrb-impact-story._en.md
- content/_partners/state-and-local._en.md
Visually unchanged, but the markup is updated
| --- | --- |
| <img width="1363" alt="Screen Shot 2022-06-02 at 3 46 39 PM" src="https://user-images.githubusercontent.com/458784/171750571-cef33f2b-8a7d-4ff7-ab89-6c7463d77508.png"> |  <img width="1351" alt="Screen Shot 2022-06-02 at 3 46 02 PM" src="https://user-images.githubusercontent.com/458784/171750601-e82f363e-c1c1-48c8-a038-1bd947beb7d3.png"> |
> Use blockquotes for quotes (LG-6487)

- _layouts/partners/faq.html
- assets/js/faqs.js
https://cm-jira.usa.gov/browse/LG-6486
> LG-6486 - Expand/collapse in FAQ can be more descriptive

- _data/en/settings.yml
- _data/es/settings.yml
- _data/fr/settings.yml
- content/_policy/about-us._en.md
- content/_policy/about-us._es.md
- content/_policy/about-us._fr.md
This section is out of date and may invite suboptimal communication.
Let's drop it!
> Drop out of date leads list

- content/_partners/get-started._en.md
Update content for the Get Started page. 
Document from Content Review: https://docs.google.com/document/d/1K2fhyM6jf6eYRYI88IPwH3RkyEmf2Rk68xfV7Dbtjto/edit
Jira: https://cm-jira.usa.gov/browse/LG-6953
> Update content for the Get Started page

- content/_partners/faq._en.md
Update the content for our FAQ page. 
Jira: https://cm-jira.usa.gov/browse/LG-6956
> Update content on FAQ

- _layouts/partners/state-and-local.html
- content/_partners/state-and-local._en.md
See [LG-6954](https://cm-jira.usa.gov/browse/LG-6954) for more information 
[Document for Content Review](https://docs.google.com/document/d/1dADqQuJxcpc5fPJ7K2qcN4kc7ZSU4nYaLx1h8owm5n4/edit)
> Implement state and local content changes

- content/_partners/faq._en.md
This is a very small copy change.
> Use words for time window

- content/_partners/index._en.md
- content/_partners/our-services._en.md
This is just a content update. 
https://cm-jira.usa.gov/browse/LG-6947
> Update Our Services page

- _includes/partners/header.html
- _layouts/partners/faq.html
- _sass/components/_nav.scss
[JIRA Ticket ](https://cm-jira.usa.gov/browse/LG-6958)
[Figma file for reference](https://www.figma.com/file/4dgMBDwH3jDOtk86bEp1m8/%2FPartners-website-final-designs?node-id=246%3A6854)
Adding search button to all pages and removing any search bars that were previously in the sidebar (not header)
> Implement the /partners search button on all pages

- _data/en/settings.yml
- _data/es/settings.yml
- _data/fr/settings.yml
- _includes/contact_form.html
> LG-6676: subtopics added

- content/_help/get-started/authentication-options._es.md
- content/_help/verify-your-identity/accepted-state-issued-identification._en.md
- content/_help/verify-your-identity/accepted-state-issued-identification._es.md
- content/_help/verify-your-identity/accepted-state-issued-identification._fr.md
- content/_help/verify-your-identity/how-to-add-images-of-your-state-issued-id._en.md
There were several markdown files that contained extra characters (likely added by the CMS). Those extra characters made it to production, and have been visible for a while now. This PR removes those extra characters, and does a small amount of in-file cleanup.
> Remove unnecessary characters

- _includes/footer.html
- _includes/partners/header.html
- content/_landing/index._en.md
- content/_landing/index._es.md
- content/_landing/index._fr.md
- content/_landing/state-and-local._en.md
- content/_landing/state-and-local._es.md
- content/_landing/state-and-local._fr.md
- content/_landing/who_uses_login._en.md
- content/_landing/who_uses_login._es.md
- content/_landing/who_uses_login._fr.md
- content/_policy/contact._en.md
- content/_policy/contact._es.md
- content/_policy/contact._fr.md
- spec/all_pages_spec.rb
- spec/support/matchers.rb
This pr should be merged _after_ the site is lived and has been tested.
> Update redirects for the new partners site

- content/_landing/404.md
This is a placeholder for soon to be available partners site.
> LG-6529 Partners site: Develop a 404 experience

- _includes/partners/contact.html
- assets/js/partners/contact.js
> Add client-side validation of email address for partner contact form

- _layouts/partners/state-and-local.html
- _sass/components/partners/_partners.scss
- content/_partners/state-and-local._en.md
This adds a disclaimer about funding for state and local partners.
> add-disclaimer

- _layouts/partners/state-and-local.html
- _sass/components/partners/_partners.scss
Ugh - forgot to push before merging my last pr 🤦‍♀️ https://github.com/18F/identity-site/pull/966
> Cleanup based on feedback

- _data/en/settings.yml
- _data/es/settings.yml
- _data/fr/settings.yml
[LG-7795](https://cm-jira.usa.gov/browse/LG-7795)
Please double check two issues before merging:
1. Verify the change is made at the correct place
2. Note that this change potentially conflicts with the work at https://github.com/18F/identity-site/commit/c7150f4d6a61e46d7345454d0df28e1d872860c9. Both changes are presumably necessary.
>  LG-7795: Update contact center availability

- _data/en/settings.yml
- _data/es/settings.yml
- _data/fr/settings.yml
This PR updates the phone number hours of operation from 11 am - 8 pm est to 8 am - 8 pm est.
> Update the contact center phone number hours of operation

- _data/en/settings.yml
- _data/es/settings.yml
- _data/fr/settings.yml
- _data/nav.yml
- _includes/components/footer-navigation.html
- _includes/footer.html
- _includes/header--help.html
- _includes/header.html
- _includes/partners/footer.html
- _includes/partners/header.html
- _layouts/partners/contact.html
- _layouts/partners/faq.html
- _sass/components/_footer.scss
- _sass/pages/_partners.scss
- spec/e2e/accessibility_spec.js
Why?
- Avoid duplication between partners and main brochure sites
- Resolve accessibility issues
- Bring layout styling into closer alignment with design specification
- Simplify markup and stylesheet implementation
> LG-8558: Refactor footer as shared component

- _layouts/contact_us.html
- content/_policy/contact._en.md
- content/_policy/contact._es.md
- content/_policy/contact._fr.md
Reverts 18F/identity-site#1026
> Revert "Add outage message for Salesforce outage"

- content/_help/verify-your-identity/verify-your-identity-in-person._en.md
- content/_help/verify-your-identity/verify-your-identity-in-person._es.md
- content/_help/verify-your-identity/verify-your-identity-in-person._fr.md
[Lg-8501](https://cm-jira.usa.gov/browse/LG-8501)
Update help center content for nationwide launch 
En
<details>
<summary>Before Verify your identity in person En:</summary>
</details>
<details>
<summary>After Verify your identity in person En:</summary>
</details>
<details>
<summary>Before Complete the process En:</summary>
</details>
<details>
<summary>After Complete the process En:</summary>
</details>
Es:
<details>
<summary>Before Verify your identity in person Es:</summary>
</details>
<details>
<summary>After Verify your identity in person Es:</summary>
</details>
<details>
<summary>Before Complete the process Es:</summary>
</details>
<details>
<summary>After Complete the process Es:</summary>
</details>
Fr:
<details>
<summary>Before Verify your identity in person fr:</summary> …
> update help center content to reflect nationwide launch content

- _layouts/contact_us.html
- content/_policy/contact._en.md
- content/_policy/contact._es.md
- content/_policy/contact._fr.md
Redo of #1026 because we have a new outage
> Add outage message for Salesforce outage

- content/_help/verify-your-identity/how-to-verify-your-identity._en.md
- content/_help/verify-your-identity/how-to-verify-your-identity._es.md
- content/_help/verify-your-identity/how-to-verify-your-identity._fr.md
JIRA: https://cm-jira.usa.gov/browse/LG-8707
> LG-8707 update "How to verify your identity"

- _data/en/settings.yml
- _data/es/settings.yml
- _data/fr/settings.yml
Added the agencies to contact center,
Currently waiting for Salesforce side to add these to their production so that this can be merged on our side.
Since myTreasury and Pay.gov are like website names I dont think they need to be translated.
> LG-8863: add contact center agencies

- _config.yml
- _includes/contact_form.html
- assets/js/contact.js
- package-lock.json
- package.json
- spec/output_spec.rb
This reverts commit 944793016db248411383bb87758ae778ebc3c627 (#1063)
[Slack context](https://gsa-tts.slack.com/archives/C0NGESUN5/p1680022455899929?thread_ts=1679931537.439049&cid=C0NGESUN5): we found a way to block spam on the backend
> Remove contact form spam email blocking

- content/_help/verify-your-identity/phone-number._en.md
- content/_help/verify-your-identity/phone-number._es.md
- content/_help/verify-your-identity/phone-number._fr.md
Updated the content for `help/verify-your-identity/phone-number/`
If relevant, include a screenshot or screen capture of the changes.
Before:
After:
> LG-9359 Update "Verify your phone number" help center content

- _data/en/settings.yml
- _data/es/settings.yml
- _data/fr/settings.yml
- _includes/components/footer-navigation.html
Translations from Gengo.
[LG-9623](https://cm-jira.usa.gov/browse/LG-9623)
> LG-9623: 508 - Insufficient text alternative for static Login.gov logo

- content/_help/verify-your-identity/verify-your-identity-in-person._en.md
- content/_help/verify-your-identity/verify-your-identity-in-person._es.md
- content/_help/verify-your-identity/verify-your-identity-in-person._fr.md
[Lg-9029](https://cm-jira.usa.gov/browse/LG-9029)
NOTE: THIS PR SHOULD NOT BE MERGED UNTIL THE DAV WORK IS RELEASED
This pr removes the references to a secondary id on the ipp help center page. There are 2 sections removed from the page. 
[Preview link](https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/18f/identity-site/shannon/lg-9029-remove-secondary-id-refs/help/verify-your-identity/verify-your-identity-in-person/)
<details>
<summary> En before:</summary>
</details>
<details>
<summary> En after:</summary>
</details>
<details>
<summary> Es before:</summary>
</details>
<details>
<summary> Es after:</summary>
</details>
<details>
<summary> Fr before:</summary>
</details>
<details>
<summary> Fr after:</summary>
</details>
> LG-9029 remove secondary id refs from ipp help page

- content/_help/manage-your-account/change-your-email-address._en.md
- content/_help/manage-your-account/change-your-email-address._es.md
- content/_help/manage-your-account/change-your-email-address._fr.md
- content/_help/manage-your-account/change-your-phone-number._en.md
- content/_help/manage-your-account/change-your-phone-number._es.md
- content/_help/manage-your-account/change-your-phone-number._fr.md
- content/_help/manage-your-account/international-phone-support._en.md
- content/_help/manage-your-account/international-phone-support._es.md
- content/_help/manage-your-account/international-phone-support._fr.md
- content/_help/manage-your-account/personal-key._en.md
- content/_help/manage-your-account/personal-key._es.md
- content/_help/manage-your-account/personal-key._fr.md
- content/_help/manage-your-account/relink-your-accounts._en.md
- content/_help/manage-your-account/relink-your-accounts._es.md
- content/_help/manage-your-account/relink-your-accounts._fr.md
- content/_help/trouble-signing-in/forgot-your-personal-key._en.md
- content/_help/trouble-signing-in/forgot-your-personal-key._es.md
- content/_help/trouble-signing-in/forgot-your-personal-key._fr.md
[LG-9545](https://cm-jira.usa.gov/browse/LG-9545)
Adding a help center article for Personal Key.
Trouble Signing In
Manage Your Account:
EN:
ES:
FR:
> LG-9545 Help Center article about Personal Key

- content/_help/trouble-signing-in/face-or-touch-unlock._en.md
- content/_help/trouble-signing-in/face-or-touch-unlock._es.md
- content/_help/trouble-signing-in/face-or-touch-unlock._fr.md
- content/_help/trouble-signing-in/overview._en.md
- content/_help/trouble-signing-in/overview._es.md
- content/_help/trouble-signing-in/overview._fr.md
F/T Unlock help page: https://cm-jira.usa.gov/browse/LG-10200
Adds new page thats more detailed for F/T unlock
> LG-10200: New F/T unlock help page

- content/_help/verify-your-identity/accepted-state-issued-identification._en.md
- content/_help/verify-your-identity/accepted-state-issued-identification._es.md
- content/_help/verify-your-identity/accepted-state-issued-identification._fr.md
[LG-10329](https://cm-jira.usa.gov/browse/LG-10329)
Added mention of expiration dates for accepted state-issued IDs.
English:
Spanish:
French:
> Added mention of expiration dates to state issued identification

- content/_help/get-started/authentication-options._en.md
- content/_help/get-started/authentication-options._es.md
- content/_help/get-started/authentication-options._fr.md
🎫 Ticket
[LG-10168](https://cm-jira.usa.gov/browse/LG-10168)
🛠 Summary of changes
Per ticket above, adding face and touch language to available authentication options page. This branch shouldn't be merged until face and touch unlock is relaunched in phase one as it no longer has the "This option is no longer available" text.
Additional commits include a few minor changes for line consistency as well as an edit to the alert style code which was incorrect in the first commit.
> Update authentication options page with new face and touch unlock language

- _includes/meta.html
- _includes/partners/footer.html
- content/_help/get-started/authentication-methods._es.md
- content/_help/get-started/authentication-methods._fr.md
- content/_help/manage-your-account/add-or-change-your-authentication-method._en.md
- content/_help/manage-your-account/add-or-change-your-authentication-method._es.md
- content/_help/manage-your-account/add-or-change-your-authentication-method._fr.md
- content/_help/verify-your-identity/verify-your-identity-in-person._en.md
- content/_help/verify-your-identity/verify-your-identity-in-person._es.md
- content/_help/verify-your-identity/verify-your-identity-in-person._fr.md
- content/_landing/404.md
- content/_partners_impact_stories/sba._en.md
This PR:
- Resolve merge conflicts found in #1138 because the `/authentication-options` route got renamed to `/authentication-methods` and could not be easily reconciled without blowing away changes or introducing regressions.
> Restore-LG-9552-upper-case-Login

- _includes/meta.html
- content/_help/specific-agencies/trusted-traveler-programs._en.md
- content/_help/specific-agencies/trusted-traveler-programs._es.md
- content/_help/specific-agencies/trusted-traveler-programs._fr.md
[LG-9988](https://cm-jira.usa.gov/browse/LG-9988)
"global entry" searches account for 3 of the top 10 searches on Login.gov (#1, #3, and #7 in May 2023), yet "global entry" does not produce any useful results when searching:
https://search.usa.gov/search?utf8=%E2%9C%93&affiliate=login.gov&query=global+entry
This, despite the fact that we have a dedicated page for Trusted Traveler Programs (TTP), where TTP includes Global Entry:
https://login.gov/help/specific-agencies/trusted-traveler-programs/
At the very least, this page should show up as a result when searching for search terms related to Trusted Traveler Programs.
Related Slack discussions:
https://gsa-tts.slack.com/archives/C01710KMYUB/p1685621538459719
[https://gsa-tts.slack.com/archives/C01710KMYUB/p1683004302945769?](https://gsa-tt …
> add keyword meta tag and list of keywords for trusted traveler programs page

- content/_help/verify-your-identity/accepted-identification-documents._en.md
> LG-10526: typo fix

- _includes/already_have_an_account_banner.html
- _includes/components/3-col.html
- _includes/components/create-an-account.html
- _includes/components/icon-list.html
- _includes/components/icon.html
- _includes/language_picker.html
(recommended vieweing with `?w=1`)
For the most part our codebase indents by 2, but these partials had a mix, so I updated them.
> Update partials to indent by 2 spaces

- .eslintignore
Removes a reference to a file which no longer exists.
The referenced file was removed in #923.
`npm run lint`
> Remove lingering reference to jQuery

- content/_help/verify-your-identity/verify-your-identity-in-person/find-a-participating-post-office._en.md
- content/_help/verify-your-identity/verify-your-identity-in-person/find-a-participating-post-office._es.md
- content/_help/verify-your-identity/verify-your-identity-in-person/find-a-participating-post-office._fr.md
[LG-10300](https://cm-jira.usa.gov/browse/LG-10300)
see [18F/identity-idp/pull/9172](https://github.com/18F/identity-idp/pull/9172)
> LG-10300: Add translations for location search redirect alert

- content/_landing/create_an_account._en.md
- content/_landing/create_an_account._es.md
- content/_landing/create_an_account._fr.md
[LG-10838](https://cm-jira.usa.gov/browse/LG-10838)
Adds **Face or touch unlock** to list of More secure authentication options.
Correct phrasing of Text/Voice messaging and uncapitalize "Key" @ Security key option.
> add Face or touch unlock to authentication methods example

- scripts/TOUCHPOINTS.md
Reformats the Touchpoint script README to be more in line with other markdown files in this repository.
> reformat the Touchpoint script README

- _data/en/settings.yml
- _data/es/settings.yml
- _data/fr/settings.yml
[LG-10077](https://cm-jira.usa.gov/browse/LG-10077)
Changes on the Salesforce side may have already been made (from a previous ticket).
Visual representation of values are presumed to be correct from the Slack request. Translations have been confirmed.
> LG-10077: Add Department of State MyTravelGov to Contact form

- .circleci/config.yml
- _data/en/settings.yml
- _data/es/settings.yml
- _data/fr/settings.yml
Enforces YAML linting in CircleCI.
The [job was already defined](https://github.com/18F/identity-site/blob/a47f36272f90e4659d36ef35262df8659bbf5716/.circleci/config.yml#L129-L137), it just wasn't included in the workflow. This resolves that.
See discussion: https://github.com/18F/identity-site/pull/1178#discussion_r1365528792
1. Observe that this initial commit fails. A follow-up commit to fix the current issues will be committed to make the build pass.
> Run lint-yaml job in CircleCI workflow

- content/_help/specific-agencies/ssa._en.md
- content/_help/specific-agencies/ssa._es.md
- content/_help/specific-agencies/ssa._fr.md
[LG-10933](https://cm-jira.usa.gov/browse/LG-10933)
Created a help article for Social Security Administration under help for specific agencies section. Included with the translated copy meta keywords to boost search relevance within search.gov
> Add a page to help section for SSA.org

- content/_help/specific-agencies/ssa._en.md
- content/_help/specific-agencies/ssa._es.md
- content/_help/specific-agencies/ssa._fr.md
Update to the title on newly added article from [https://github.com/18F/identity-site/pull/1178](PR 1178)
> LG-10933 Add Help Article for Social Security Administration

- content/_help/verify-your-identity/how-to-verify-your-identity._en.md
- content/_help/verify-your-identity/how-to-verify-your-identity._es.md
- content/_help/verify-your-identity/how-to-verify-your-identity._fr.md
- content/_help/verify-your-identity/phone-number._en.md
- content/_help/verify-your-identity/phone-number._es.md
- content/_help/verify-your-identity/phone-number._fr.md
- content/_help/verify-your-identity/verify-your-address-by-mail._en.md
- content/_help/verify-your-identity/verify-your-address-by-mail._es.md
- content/_help/verify-your-identity/verify-your-address-by-mail._fr.md
- content/_help/verify-your-identity/verify-your-identity-in-person._en.md
- content/_help/verify-your-identity/verify-your-identity-in-person._es.md
- content/_help/verify-your-identity/verify-your-identity-in-person._fr.md
[LG-10726](https://cm-jira.usa.gov/browse/LG-10726)
Standardize on '5 to 10 days' rather than '3-7 business days' or other phrases for the length of time a letter takes to reach the user in Verify by Mail. Language in the IDP has already been changed.
~PR is up for discussion of changes with @artfulaction. Spanish and French translations will be added before this is merged.~ Now ready for review.
[Review site](https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/18f/identity-site/sonia-lg-10726-update-verify-by-mail-dates/). Pages edited in English, Spanish, and French:
- [How to verify your identity](https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/18f/identity-site/sonia-lg-10726-update-verify-by-mail-dates/help/verify …
> LG-10726 Change date language around verify by mail

- _data/en/settings.yml
- _data/es/settings.yml
- _data/fr/settings.yml
https://cm-jira.usa.gov/browse/LG-11547
Remove unused agency in agency list
> LG-11547: Remove unused category

- _data/en/settings.yml
- _data/es/settings.yml
- _data/fr/settings.yml
[LG-11710: add agencies to dropdown](https://cm-jira.usa.gov/browse/LG-11710)
Add new agencies
> LG-11710: add new agencies to dropdown

- README.md
I had a missing quote in README of this [PR# 1198](https://github.com/18F/identity-site/pull/1198)
- Add missing quote in README
> Add Missing Quote in README

- content/_help/specific-agencies/ssa._en.md
- content/_help/specific-agencies/ssa._es.md
- content/_help/specific-agencies/ssa._fr.md
[LG-12133](https://cm-jira.usa.gov/browse/LG-12133)
This PR revises the first sentence on the Social Security Administration help page
See the revised sentence on the following pages:
](https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/18f/identity-site/jd-update-ssa-help-page/es/help/specific-agencies/ssa/)
> update first sentence of SSA article

- _data/en/settings.yml
- _data/es/settings.yml
- _data/fr/settings.yml
Reverts 18F/identity-site#1200
Discussion: https://gsa-tts.slack.com/archives/C05MGJ72GU9/p1706128020935619?thread_ts=1706116913.101349&cid=C05MGJ72GU9
> Revert "LG-12119: Add agency NCUA to contact form"

- _data/en/settings.yml
- _data/es/settings.yml
- _data/fr/settings.yml
[LG-12119](https://cm-jira.usa.gov/browse/LG-12119)
Re-adds the agency NCUA to the contact form, reverting the previous revert.
<!--
> LG-12119: Add agency NCUA to contact form (v2)

- _data/en/settings.yml
- _data/es/settings.yml
- _data/fr/settings.yml
[LG-12121](https://cm-jira.usa.gov/browse/LG-12121)
This PR changes the  .gov Registrar value to Get .gov
If relevant, include a screenshot or screen capture of the changes.
| ![image](https://github.com/18F/identity-site/assets/17969963/02b27567-60da-4f7c-9cde-4128d2b3d312) | ![image](https://github.com/18F/identity-site/assets/17969963/05e552a4-d5f7-4165-8c6e-5b9640474166) |
> LG-12121: Contact Us - Change ".gov Registrar" to "Get .gov"

- content/_help/verify-your-identity/how-to-verify-your-identity._en.md
- content/_help/verify-your-identity/how-to-verify-your-identity._es.md
- content/_help/verify-your-identity/how-to-verify-your-identity._fr.md
- content/_help/verify-your-identity/overview._en.md
- content/_help/verify-your-identity/overview._es.md
- content/_help/verify-your-identity/overview._fr.md
[LG-11843](https://cm-jira.usa.gov/browse/LG-11843)
Currently on the login.gov help sidebar if you click 'Verify your identity' you get redirected to /help/verify-your-identity/how-to-verify-your-identity this PR fixes the redirect to go to /help/verify-your-identity/overview
> LG-11843 Verify your identity in help center links to overview

- _plugins/escape_quotes.rb
- _plugins/idp_translations.rb
Attempts to fix a couple minor issues identified by CodeQL.
> Fix CodeQL findings

- admin/config.yml
- package.json
Updates references to the previous 18F GitHub organization for sites migrated to the GSA-TTS organization.
> Update GitHub org references

- _data/en/settings.yml
- _data/es/settings.yml
- _data/fr/settings.yml
[LG-12807](https://cm-jira.usa.gov/browse/LG-12807)
This ticket updates "Get .gov" on the dropdown menu to "Get.gov"
Current state:
Preview of update:
**NOTE**: The "Get .gov" value id will be updated by Salesforce, therefore there is no change on that value.
> LG-12807: Update "Get.gov" value

- content/_partners_impact_stories/rrb._en.md
fixes small but important typo for https://cm-jira.usa.gov/browse/LG-12792
> Fixes typo

- content/_help/verify-your-identity/verify-your-identity-in-person._es.md
- content/_help/verify-your-identity/verify-your-identity-in-person._fr.md
[LG-12803](https://cm-jira.usa.gov/browse/LG-12803)  Update translations for: Help Center content for new opt-in IPP flow
* Update Verify Your Identity In Person view with DOS Translations in Spanish and French.
* Added "verify your identity online" link to the Spanish and French page. It was already on the English page. The link will take you to "/help/verify-your-identity/how-to-verify-your-identity" in the language you came from. 
* Added "Find a Participating Post Office" link to the Spanish and French page. It was already on the English page. The link will take you to "/help/verify-your-identity/verify-your-identity-in-person/find-a-participating-post-office/" in the language you came from. 
**Spanish**
**French**
> LG-12803- Update translations for: Help Center content for new opt-in IPP flow

- content/_partners/state-and-local._en.md
[LG-12740](https://cm-jira.usa.gov/browse/LG-12740)
This change replaces two paragraphs entirely from the document:
https://docs.google.com/document/d/13NqvGkkPqlM2R_SgAZmiK_L90-s_B3iNTL3ce5Odaxo/edit. 
This PR updates the page:
- /partners/state-and-local/
https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/LG-12740-Q2-updates-v2/partners/state-and-local/
> LG-12740: Q2 Updates to Content v2

- _data/en/settings.yml
- _data/es/settings.yml
- _data/fr/settings.yml
- _data/zh/settings.yml
Updates language picker content for Chinese.
If relevant, include a screenshot or screen capture of the changes.
| ![image](https://github.com/GSA-TTS/identity-site/assets/1430443/1b710dcc-d52b-4edf-a5d4-bc6cb200525e)  | ![image](https://github.com/GSA-TTS/identity-site/assets/1430443/4ba11b26-af11-4860-a9dd-246197eb1932)  |
> update Chinese content for language picker

- content/_help/verify-your-identity/how-to-add-images-of-your-state-issued-id._en.md
- content/_help/verify-your-identity/how-to-add-images-of-your-state-issued-id._es.md
- content/_help/verify-your-identity/how-to-add-images-of-your-state-issued-id._fr.md
**🛑 -- DO NOT MERGE until we have a green light for biometrics -- 🛑**
[LG-12795](https://cm-jira.usa.gov/browse/LG-12795)
Updates the text and translations according to the linked ticket.
Compare the text in the translations to the text on the pages for:
| ![Screenshot 2024-04-10 at 1 02 24 PM](https://github.com/GSA-TTS/identity-site/assets/35475380/7d6b337a-3945-4149-b85f-242f05aba182) | ![Screenshot 2024-04-10 at 12 43 04 PM](https://github.com/GSA-TTS/identity-site/assets/35475380/34373a3a-3229-4abe-bf81-897cd8264508) |
| ![Screenshot 2024-04-10 at 1 02 53 PM](https://github.com/GSA-TTS/identity-site/assets/35475380/807e75eb-6e58-4221-afab-313368ed1594) | ![Screenshot 2024-04-10 at 12 43 …
> LG-12795: Update text for How to add images pages - DO NOT MERGE UNTIL APPROVAL

- content/_help/manage-your-account/personal-key._es.md
- content/_help/manage-your-account/personal-key._fr.md
[LG-13200](https://cm-jira.usa.gov/browse/LG-13200)
> changelog: User-Facing Improvements, Authentication, update translations

- _data/language_map.yml
- spec/data_spec.rb
[LG-13226](https://cm-jira.usa.gov/browse/LG-13226)
This changes the value of 'Chinese' to 'Simplified Chinese' on the contact form to match the value expected by Salesforce.
> LG-13226: SF Auto Email Response Template in Chinese

- content/_help/verify-your-identity/how-to-verify-your-identity._en.md
[LG-13529](https://cm-jira.usa.gov/browse/LG-13529)
The title previously read "Verify your identity" instead of "How to verify your identity". This change fixes that.
Before:
After:
> LG-13529 | Updates title on 'How to verify your identity'

- content/_help/verify-your-identity/how-to-add-images-of-your-state-issued-id._zh.md
This pull request is the final LQA update from DOS for Chinese (Simplified). Spacing in the code is removed, which removes inaccurate spacing in the translated content.
> Final Chinese (Simplified) LQA fix

- spec/e2e/accessibility_spec.js
Improves performance of accessibility end-to-end tests by inverting the hierarchy of testing pages across varying viewport sizes:
- Before: For each viewport size, created new tab, navigated to a page, and ran accessibility checks
- After: Create tab and navigate to a page, then run accessibility checks for each viewport size
The key difference is that we're not creating a new tab and navigating to the page multiple times, instead navigating once and changing the viewport size after the page has loaded.
**Performance impact:**
Average of 5 runs in CircleCI.
**Before:** 3m53s
**After:** 3m30s
**Diff:** -23s (-5.5%)
Not as big an impact as I was hoping, but an improvement all the same.
```
make build
NODE_ENV=test node --import=esbuild-esm-loader/register --import=./spec/spec_helper.js …
```
> Improve performance of accessibility end-to-end tests

- content/_policy/messaging._en.md
- content/_policy/messaging._zh.md
[LG-13654](https://cm-jira.usa.gov/browse/LG-13654)
> LG-13654: Fix Typo on Terms and Conditions Page

- content/_help/manage-your-account/add-or-change-your-authentication-method._en.md
- content/_help/manage-your-account/add-or-change-your-authentication-method._es.md
- content/_help/manage-your-account/add-or-change-your-authentication-method._fr.md
[LG-13639](https://cm-jira.usa.gov/browse/LG-13639)
> update change content page

- content/_help/verify-your-identity/verify-your-identity-in-person._en.md
- content/_help/verify-your-identity/verify-your-identity-in-person._es.md
- content/_help/verify-your-identity/verify-your-identity-in-person._fr.md
- content/_help/verify-your-identity/verify-your-identity-in-person._zh.md
[LG-13832](https://cm-jira.usa.gov/browse/LG-13832)
Removes GPO related content from the in-person proofing help article, particularly the sentence:
"If you cannot complete this step, we can [send you a verification code by mail](https://login.gov/help/verify-your-identity/verify-your-address-by-mail/) which takes 5 to 10 days to arrive."
Steps to confirm the changes locally:
<kbd><img width="700" alt="Screenshot 2024-07-11 at 10 34 26 AM" src="https://github.com/GSA-TTS/identity-site/assets/8674959/6fbe5ef3-1774-4242-995f-89b04acc977a"></kbd>
<kbd><img width="700" alt="Screenshot 2024-07-11 at 10 34 06 AM" src="https://github.com/GSA-TTS/identity-site/assets/8674959/be07475c-bd6b-47b2-a721-e962bbd7a08e"></kbd>
<kbd><img width="700" alt="Screenshot 2024-07-11 at 3 56 29 PM" …
> LG-13832 Remove GPO-related content from verify in-person help page

- _includes/header--help.html
- _includes/help/nav_sidenav.html
- content/_help/trouble-signing-in/security-check-failed._en.md
- content/_help/trouble-signing-in/security-check-failed._es.md
- content/_help/trouble-signing-in/security-check-failed._fr.md
- content/_help/trouble-signing-in/security-check-failed._zh.md
[LG-13571](https://cm-jira.usa.gov/browse/LG-13571)
Adds a new help article "Security check failed (reCAPTCHA)".
Because this feature is not yet enabled in production, it is hidden from navigation and from the sitemap (to avoid indexing in search results). A follow-up ticket will make the page accessible from search and navigation, closer to when the feature is ready to go live.
Verify that the page is not surfaced in navigation (both desktop and mobile).
1. Go to https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/aduth-lg-13571-help-recaptcha/help/trouble-signing-in/overview/
2. Try to navigate to the new page
3. Observe that you fail!
Verify that the page is not listed in the sitemap:
1. Go to …
> LG-13571: Add "Security check failed (reCAPTCHA)" help article

- content/_help/verify-your-identity/verify-your-identity-in-person._en.md
- content/_help/verify-your-identity/verify-your-identity-in-person._es.md
- content/_help/verify-your-identity/verify-your-identity-in-person._fr.md
- content/_help/verify-your-identity/verify-your-identity-in-person._zh.md
[LG-13539](https://cm-jira.usa.gov/browse/LG-13539)
Modify some content on the "Verify your identity in person" article in the Help Center to reflect opt-in.
This includes the "We’ll email you with next steps" section and the "What to do if you were unable to successfully verify your identity in person" section, both on the "verify-your-identity-in-person" help center page.
| | Before | After |
| ------------- | ------------- | ------------- |
| English | <img width="555" alt="Screenshot 2024-07-19 at 12 35 48 PM" src="https://github.com/user-attachments/assets/7053278e-ebc2-4342-adeb-926b5508fc83"> | <img width="536" alt="Screenshot 2024-07-19 at 12 35 54 PM" …
> LG-13539 Modify help center troubleshooting content to reflect opt-in

- _data/en/settings.yml
- _data/es/settings.yml
- _data/fr/settings.yml
- _data/zh/settings.yml
[LG-14096](https://cm-jira.usa.gov/browse/LG-14096)
Added values can be seen on the form here:
- https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/LG-14096-add-agencies-contact-us/contact/
Adds two new values to the "Contact Us" form found at `/contact/`.
A request for translations of these values will be made. However, the current request is to add these values as they are in a time sensitive fashion. A follow-up change will be made if translations are returned.
> LG-14096: Add 2 new agencies to Contact Us Form

- content/_partners/state-and-local._en.md
[LG-14088](https://cm-jira.usa.gov/browse/LG-14088)
Note: Content changes approved here https://gsa-tts.slack.com/archives/C06S329FUA2/p1722890894649339?thread_ts=1722888380.702809&cid=C06S329FUA2.
Updates content at the following location
- `/partners/state-and-local/`
- https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/LG-14088-revise-state-local/partners/state-and-local/
> LG-14088: Revise content, partners/state-and-local/

- content/_help/specific-agencies/ssa._en.md
- content/_help/specific-agencies/ssa._es.md
- content/_help/specific-agencies/ssa._fr.md
- content/_help/specific-agencies/ssa._zh.md
[LG-14091](https://cm-jira.usa.gov/browse/LG-14091)
Accepted here: https://gsa-tts.slack.com/archives/C06S329FUA2/p1723218386885049?thread_ts=1723163289.200969&cid=C06S329FUA2
Changes can be seen at the following location:
- https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/LG-14091-update-ssa-help-article/help/specific-agencies/ssa/
> LG-14091: Update SSA help article

- content/_help/verify-your-identity/overview._zh.md
[LG-14134](https://cm-jira.usa.gov/browse/LG-14134)
Updates Chinese translation of the [Verify your identity](https://login.gov/help/verify-your-identity/overview/) article.
Preview: https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/matthinz/14134-verify-your-id-overview-zh-translation/zh/help/verify-your-identity/overview/
> LG-14134: Updated Chinese translations for "Verify your identity" article

- _config.yml
- _includes/contact_form.html
- assets/js/populate_contact_form_agency.js
Salesforce provided an email today with new values for hidden fields.
Link to chat with new values mentioned: https://gsa-tts.slack.com/archives/C06S329FUA2/p1723749451669159?thread_ts=1721249527.349409&cid=C06S329FUA2
[LG-14228](https://cm-jira.usa.gov/browse/LG-14228)
- Changes hidden field values at `/contact/`.
> LG-14228: Add new Salesforce hidden field values

- content/_help/verify-your-identity/overview._zh.md
We renamed "How to add images of your state issued id" to "How to take photos to verify your identity" this was not fixed in the new zh translations.
> fix a now unused link in the zh translation for verify-your-identity

- content/_help/verify-your-identity/how-to-take-photos-to-verify-your-identity._es.md
- content/_help/verify-your-identity/how-to-take-photos-to-verify-your-identity._fr.md
- content/_help/verify-your-identity/how-to-take-photos-to-verify-your-identity._zh.md
- content/_help/verify-your-identity/overview._en.md
- content/_help/verify-your-identity/overview._es.md
- content/_help/verify-your-identity/overview._fr.md
- content/_help/verify-your-identity/overview._zh.md
[LG-14249](https://cm-jira.usa.gov/browse/LG-14249)
The links about taking a photo of your self are now updated to link to the "How to take photos of yourself" section of How to take photos to verify your identity.
> LG-14249 Update Related Articles links for "How to take a photo of yourself"

- _data/en/settings.yml
- _data/es/settings.yml
- _data/fr/settings.yml
- _data/zh/settings.yml
- _layouts/contact_us.html
[LG-13890](https://cm-jira.usa.gov/browse/LG-13890)
Updates the value "SBA DLAP" to "SBA" and removes two values from the common section of the same dropdown.
Translations for "SBA" will be requested in a separate ticket.
The updated values can be seen on the form at:
- https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/LG-13890-remove-sba-dlap/contact/
> LG-13890: Update SBA DLAP to SBA

- content/_help/trouble-signing-in/security-check-failed._en.md
- content/_help/trouble-signing-in/security-check-failed._es.md
- content/_help/trouble-signing-in/security-check-failed._fr.md
- content/_help/trouble-signing-in/security-check-failed._zh.md
[LG-13952](https://cm-jira.usa.gov/browse/LG-13952)
Removes the [xclude_from_nav and sitemap](https://github.com/GSA-TTS/identity-site/blob/ab0cd569e7faae0af34a2a3a3e3feaee44da56d6/content/_help/trouble-signing-in/security-check-failed._en.md#L7-L8) flags from the new page.
> LG-13952 Expose reCAPTCHA help page on Help Center

- _data/en/settings.yml
- _data/es/settings.yml
- _data/fr/settings.yml
- _data/zh/settings.yml
[LG-14378](https://cm-jira.usa.gov/browse/LG-14378)
> LG-14378: Add State of Maryland

- _data/zh/settings.yml
- content/_help/verify-your-identity/overview._zh.md
[LG-14496](https://cm-jira.usa.gov/browse/LG-14496)
Fixes a few Chinese translation issues identified during LQA. The feedback was for the "Verify your identity" page, but a couple of changes (Touchpoints Yes/No buttons, as well as a link in the footer) are global changes.
[See the preview page here](https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/matthinz/lg-14496-zh-fixes/zh/help/verify-your-identity/overview/)
> LG-14496: Chinese translation LQA fixes

- content/_help/verify-your-identity/how-to-take-photos-to-verify-your-identity._zh.md
Update alt text and captions for help center illustrations in Simplified Chinese w Signed Commits
[LG-14512](https://cm-jira.usa.gov/browse/LG-14512)
Updated chinese alt text based of lqa revisions.
> LG-14512  Update alt text and captions for help center illustrations in Simplified Chinese w Signed Commits

- _data/en/settings.yml
- _data/es/settings.yml
- _data/fr/settings.yml
- _data/zh/settings.yml
- _includes/contact_form.html
This should be accepted [here](https://gsa-tts.slack.com/archives/C06S329FUA2/p1728592023888149) shortly.
[LG-14190](https://cm-jira.usa.gov/browse/LG-14190)
> LG-14190: Update contact us form topics

- _includes/contact_form.html
- _includes/partners/contact.html
A description of the issue can be found at the linked Jira ticket. Please also see my first comment there outlining various options.
[LG-14910](https://cm-jira.usa.gov/browse/LG-14910)
- https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/LG-14910-form-email-validation/contact/
> LG-14910: Update email inputs

- _data/es/settings.yml
[LG-14888](https://cm-jira.usa.gov/browse/LG-14888)
Updates a translation based on feedback from translators.
1. Go to https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/aduth-lg-14888-lqa/es/help/trouble-signing-in/overview/
2. Observe that "¿Tiene problemas para iniciar sesión?" is no longer showed, replaced with "¿Tiene problema para iniciar sesión?" (singular "problema")
Before|After
---|---
> LG-14888: Update Spanish strings for LQA feedback

- _data/en/settings.yml
- _data/es/settings.yml
- _data/fr/settings.yml
- _data/zh/settings.yml
[LG-14899](https://cm-jira.usa.gov/browse/LG-14899)
- https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/LG-14899-add-frb-contact-form/contact/
> LG-14899: Add value Federal Reserve Board (FRB) to form

- _config.yml
- _includes/contact_form.html
Adds a simple cleanup of the contact form. To be followed by additional changes in another ticket.
[LG-14959](https://cm-jira.usa.gov/browse/LG-14959)
- https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/LG-14959-cleanup-contact-form/contact/
> LG-14959: Cleanup contact form

- content/_help/trouble-signing-in/security-check-failed._zh.md
[LG-14888](https://cm-jira.usa.gov/browse/LG-14888)
Updates content from the "Security Check Failed" Help Center article based on feedback from LQA translators.
Related Slack discussion: https://gsa-tts.slack.com/archives/C0595QABDS7/p1730835763368949?thread_ts=1730831361.446239&cid=C0595QABDS7
1. Go to https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/aduth-lg-14888-chinese-lqa-recaptcha/zh/help/trouble-signing-in/security-check-failed/
2. Verify that there are no instances of the character `您` (replaced with `你`)
Before|After
---|---
> LG-14888: Update content for Security Check Failed per LQA (Chinese)

- _data/en/settings.yml
- _data/es/settings.yml
- _data/fr/settings.yml
- _data/zh/settings.yml
- content/_policy/contact._en.md
- content/_policy/contact._es.md
- content/_policy/contact._fr.md
- content/_policy/contact._zh.md
[LG-13653](https://cm-jira.usa.gov/browse/LG-13653)
- https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/LG-13653-contact-report-issue/contact/
> LG-13653: Contact report security issue

- content/_landing/join-us._en.md
- content/_landing/join-us._es.md
- content/_landing/join-us._fr.md
- content/_landing/join-us._zh.md
[LG-15062](https://cm-jira.usa.gov/browse/LG-15062)
- https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/LG-15062-update-tts-urls/join/#how-to-apply
> LG-15062: Update TTS urls

- content/_help/verify-your-identity/verify-your-identity-in-person/issues-with-verifying-your-identity-in-person._es.md
- content/_help/verify-your-identity/verify-your-identity-in-person/issues-with-verifying-your-identity-in-person._fr.md
- content/_help/verify-your-identity/verify-your-identity-in-person/issues-with-verifying-your-identity-in-person._zh.md
[LG-15213](https://cm-jira.usa.gov/browse/LG-15213) Update languages under /issues-with-verifying-your-identity-in-person/ Help Center page
+ Added translations for Issues with verifying your identity in person view (Spanish, French, Chinese)
For each language (Spanish, French, Chinese)
English URL for article: `https://www.login.gov/help/verify-your-identity/verify-your-identity-in-person/issues-with-verifying-your-identity-in-person/`. 
| ![Screenshot 2024-12-05 at 12 54 46 PM](https://github.com/user-attachments/assets/d48e1e24-4bc2-47ff-b1b3-de3fc5d6d70d)  |  ![Screenshot 2024-12-05 at 12 57 51 PM](https://github.com/user-attachments/assets/d2c4eef2-222a-4c4d-bbef-197ddd6b516f) |
| ![Screenshot 2024-12-05 at 12 56 …
> LG-15213 Update languages for /issues-with-verifying-your-identity-in-person/

- _config.yml
- _includes/partners/header.html
- _layouts/partners/program-update.html
- _layouts/partners/program-updates.html
- _sass/components/partners/_partners.scss
- admin/config.yml
- admin/index.html
- content/_partners/faq._en.md
- content/_partners/program-updates._en.md
- spec/all_pages_spec.rb
- spec/frontmatter_spec.rb
This version applies the diff changes to avoid any potential problems with rebasing old history to sign the commits.
[LG-13755](https://cm-jira.usa.gov/browse/LG-13755)
Modify comments in `admin/config.yml` for local development. To test on staging, I previously toggled the branch name in `admin/config.yml`.
For testing the interface, go to the location `/admin/#/collections/program_updates`.
The staging path can be found at the following URL. At the time of writing, the file `admin/config.yml` is not set for the staging branch.
- https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/LG-13755-program-updates/admin/
Alternatively, you can test on your local environment by modifying comments in the file `admin/config.yml` and going to …
> LG-13755: Add program updates (signed)

- _config.yml
[LG-15326](https://cm-jira.usa.gov/browse/LG-15326)
This change permits indexing of "program updates".
> LG-15326: Remove ignore from sitemap

- content/_partners/determining-your-assurance-level._en.md
[LG-15315](https://cm-jira.usa.gov/browse/LG-15315)
Accepted [here](https://cm-jira.usa.gov/browse/LG-15315?focusedId=2150503&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2150503). 
Content updates to the page found at:
- https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/LG-15315-revise-assurance-level-page/partners/determining-your-assurance-level/
> LG-15315: Minor revisions to determining-your-assurance-level

- package-lock.json
- package.json
[LG-15477](https://cm-jira.usa.gov/browse/LG-15477)
Preview site available at:
- https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/upgrade-identity-design-system-9-4-0/
> Update identity-design-system to version 9.4.0

- content/_partners_impact_stories/dol._en.md
[LG-15587](https://cm-jira.usa.gov/browse/LG-15587)
- https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/LG-15587-revise-dol-impact-story/partners/impact-stories/dol/
> LG-15587: Revision to DOL Impact Story

- .circleci/config.yml
- content/_landing/who_uses_login._en.md
- content/_landing/who_uses_login._es.md
- content/_landing/who_uses_login._fr.md
- content/_landing/who_uses_login._zh.md
Confirmed link with outreach team.
[LG-15799](https://cm-jira.usa.gov/browse/LG-15799)
> LG-15799: Update link

- content/_policy/privacy._en.md
- content/_policy/privacy._fr.md
- content/_policy/privacy._zh.md
Please see acceptance [here](https://gsa-tts.slack.com/archives/C06S329FUA2/p1739475636630779?thread_ts=1739394590.819239&cid=C06S329FUA2).
[LG-15575](https://cm-jira.usa.gov/browse/LG-15575)
- https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/LG-15575-privacy-act-statement/policy/our-privacy-act-statement/
- https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/LG-15575-privacy-act-statement/zh/policy/our-privacy-act-statement/
> LG-15575: Update privacy act statement

- content/_policy/accessibility._en.md
- content/_policy/accessibility._es.md
- content/_policy/accessibility._fr.md
- content/_policy/accessibility._zh.md
Please see acceptance [here](https://cm-jira.usa.gov/browse/LG-15658?focusedId=2191327&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2191327).
[LG-15658](https://cm-jira.usa.gov/browse/LG-15658)
> LG-15658: Revision to accessibility page

- _data/en/settings.yml
- _data/es/settings.yml
- _data/fr/settings.yml
- _data/zh/settings.yml
Accepted [here](https://gsa-tts.slack.com/archives/C06S329FUA2/p1742932670485239?thread_ts=1742928920.463079&cid=C06S329FUA2).
[LG-15841](https://cm-jira.usa.gov/browse/LG-15841)
- https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/LG-15841-Add-agencies-contact/contact/
> LG-15841: Add agencies to contact form

- content/_help/get-started/authentication-methods._en.md
Simple content update,
[LG-15747](https://cm-jira.usa.gov/browse/LG-15747)
> LG-15747: Content update

- content/_help/trouble-signing-in/forgot-your-password._en.md
- content/_help/trouble-signing-in/forgot-your-password._es.md
- content/_help/trouble-signing-in/forgot-your-password._fr.md
- content/_help/trouble-signing-in/forgot-your-password._zh.md
Please see acceptance [here](https://gsa-tts.slack.com/archives/C06S329FUA2/p1743529552834489?thread_ts=1743528112.923109&cid=C06S329FUA2).
[LG-15905](https://cm-jira.usa.gov/browse/LG-15905)
- https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/LG-15905-add-forgot-password-personal-key-notice/help/trouble-signing-in/forgot-your-password/
- https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/LG-15905-add-forgot-password-personal-key-notice/es/help/trouble-signing-in/forgot-your-password/
- https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/LG-15905-add-forgot-password-personal-key-notice/fr/help/trouble-signing-in/forgot-yo …
> LG-15905: Add notice for forgot password personal key

- .circleci/config.yml
Alternative version for:
[LG-16153](https://cm-jira.usa.gov/browse/LG-16153)
> LG-16153: Patch external link checker (v2)

- content/_help/specific-agencies/ssa._en.md
- content/_help/specific-agencies/ssa._es.md
- content/_help/specific-agencies/ssa._fr.md
- content/_help/specific-agencies/ssa._zh.md
[LG-16146](https://cm-jira.usa.gov/browse/LG-16146)
Updates Youtube link at:
- https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/LG-16146-update-link/help/specific-agencies/ssa/
> LG-16146: Replace link on SSA help center page

- package-lock.json
- package.json
[LG-16186](https://cm-jira.usa.gov/browse/LG-16186)
Updated address-search package to match IDP.
> Update address-search package

- content/_help/specific-agencies/ssa._en.md
- content/_help/specific-agencies/ssa._es.md
- content/_help/specific-agencies/ssa._fr.md
- content/_help/specific-agencies/ssa._zh.md
[LG-16315](https://cm-jira.usa.gov/browse/LG-16315)
Removes a link from the following location. Some of the titles of the "related articles" change in English, these translations are not available in other languages yet and will be added later as part of a broader effort.
- https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/LG-16315-update-ssa-help/help/specific-agencies/ssa/
> LG-16315: Remove sentence from SSA dedicated help center article

- _data/en/settings.yml
- _data/es/settings.yml
- _data/fr/settings.yml
- _data/zh/settings.yml
Fixes https://cm-jira.usa.gov/browse/LG-16354
[LG-16354](https://cm-jira.usa.gov/browse/LG-16354)
Attached to ticket
> Add new agency applications to Contact Us page

- content/_help/verify-your-identity/overview._en.md
- content/_help/verify-your-identity/overview._es.md
- content/_help/verify-your-identity/overview._fr.md
- content/_help/verify-your-identity/overview._zh.md
[LG-16707](https://cm-jira.usa.gov/browse/LG-16707)
Removing duplicate content and adding green check mark to verify identity list
<details>
<summary>Verify My Identity Page</summary>
</details>
> LG-16707 Removing duplicate content and adding greencheck mark

- _data/en/settings.yml
- _data/es/settings.yml
- _data/fr/settings.yml
- _data/zh/settings.yml
[LG-16573: Add agency application to Contact Us form](https://cm-jira.usa.gov/browse/LG-16573)
| English | Header | Header | Header |
|--------|--------|--------|--------|
| <img width="481" height="215" alt="Screenshot 2025-09-29 at 4 15 03 PM" src="https://github.com/user-attachments/assets/6e28fdca-1196-4925-8f3f-7c8a9b3a650b" /> | <img width="607" height="141" alt="Screenshot 2025-09-29 at 4 18 54 PM" src="https://github.com/user-attachments/assets/a2a95701-7f23-4712-8914-e595fae0e661" /> | <img width="787" height="166" alt="Screenshot 2025-09-29 at 4 21 43 PM" src="https://github.com/user-attachments/assets/14620152-c93d-41b4-bce7-f63aa5e51205" /> | <img width="494" height="190" alt="Screenshot 2025-09-29 at 4 23 00 PM" src="https://github.com/user-attachments/assets/0b55d398-9300-41d …
> Add agency application to Contact Us form
