GSA-TTS/identity-site

spec/_pages/index.md_spec.rb
**Why**:
It's OK to change the copy, but we need to remember to update
NewRelic to check for the right thing when we deploy
=> Add spec that watches for the same copy as NewRelic

_includes/meta.html
Images require full URL instead of a relative path.
=> Update meta image URLs

_includes/footer.html
This PR updates the visual appearance of the footer. From issue https://github.com/18F/identity-private/issues/2073
[Preview](https://federalist.fr.cloud.gov/preview/18f/identity-site/bsh-footer)
=> New footer

_pages/developers.md
**Why** To help guide readers to information they need, we are linking specific technical terms to words in body text, not in headers.
=> Updates links to developer docs

_includes/help/nav_page_bottom.html, _includes/help/nav_page_top_small.html
Looks like we forgot to fix some translations on mobile:
=> Properly translate help page titles

_i18n/en.yml
**Why** The title of this page is "Privacy policy" and we have much more information about privacy than security. Ergo, the privacy section should be the first one. This also makes it easier for users to see both legal and plain-language privacy statements next to each other and compare.
=> Reverses placement of security and privacy section

_i18n/en.yml, _pages/developers.md, _pages/index.md
**Why**: To consolidate and organize the various email addresses, phone
numbers, and contact us CTAs across the site. Now that we have a call
center, we want them to handle most requests from the public. We want to
direct agencies interested in integrating to email partners@login.gov.
=> Update index and developer contact us footers

_includes/nav.html
When viewing the static site in a language other than English, provide a link to secure.login.gov with the correct locale.
=> Link to app with correct locale

_i18n/en.yml, _i18n/es.yml, _includes/footer.html, _includes/i18n_dropdown_desktop.html, _includes/i18n_dropdown_mobile.html
This removes the previously hardcoded list of languages from the language picker and instead builds the list based off the available locales.  Also hides the language picker entirely if no languages are available.
=> Improve language picker logic

Makefile
npm linking strategy needs to be reworked, removing for now so folks can get the site running locally without the `identity-style-guide` dependency.
=> Remove npm link from Makefile

.gitignore, package.json
- Only changes to the root css folder of the identity-style-guide were being picked up when developing with both repos locally, this expands it to all css components. (Edit: Also noticed the same was true for images and js, so expanded the paths for those as well)
- Additions to .gitignore to avoid committing shared assets.
=> Fix style-guide css watch script

package.json
Basscss and normalize.css are included in the identity-style-guide package, so we no longer need them listed as a dependency here.
=> Remove duplicate NPM packages

_includes/nav.html
**Why**:
Text was wrapping on spanish text before it
collapsed to the mobile menu. Adjust text size
just for dimensions where it would wrap.
=> Adjust text size of nav on spanish menu

_i18n/en.yml, _i18n/es.yml, _pages/index.md
Direct users to the Contact page from the homepage, rather than listing the phone number directly on the homepage.
=> Link to Contact page from Homepage

_config.yml, _i18n/en.yml, _i18n/es.yml, _i18n/fr.yml
This is the XML translations provided from translator, converted into yaml, and compiled into a single file with all of the help documentation to match the other existing locales.
Page meta descriptions were added after these translations, so there are a handful of `NOT YET TRANSLATED` values for those, but in large part this is mostly complete.
=> Add French translations

package.json
In order to keep the stylesheets organized I split them into an `app` and `static` entry point file - updating to reflect the proper stylesheet to import into the static site.
I'm using the [github branch](https://github.com/18F/identity-style-guide/pull/15) for the `identity-style-guide` npm package for testing, but once it all looks good I can bump the version of the package and update this PR to reflect.
=> Update stylesheet path

_includes/i18n_dropdown_desktop.html
Using `relative_path` was causing multiple locales to appear within the url when toggling languages.
=> Fix language dropdown

_i18n/en.yml
Check out the advisory no longer being there at https://preview.login.gov/contact/
=> Deploy production: remove contact center advisory

_includes/nav.html, _layouts/main.html, _sass/_variables.scss, _sass/components/_nav.scss
For https://github.com/18F/identity-private/issues/2296
This PR makes a few updates that prevents the navigation items from rolling over on to a new line. Accompanying style-guide changes exist [here](https://github.com/18F/identity-style-guide/pull/17). 
- Updates to `identity-style-guide@0.2.8`
=> Fix navigation for french

_includes/help/nav_page_bottom.html, _includes/help/nav_sidenav.html, _layouts/help.html
**Why**: Body content uses fancy punctuation but headers do not
**How**: Added the markdownify filter to the header content
=> Fix fancy punctuation on static site headers

_i18n/en.yml
Fix typo / remove extra word in header: https://login.gov/help/trusted-traveler-programs/whats-going-on/
=> Remove extra word from help page

_i18n/en.yml
Remove SecureAuth OTP Chrome extension since it is no longer available (returns HTTP 404 error)
=> Update list of OTP Chrome extensions

_i18n/es.yml, _i18n/fr.yml
**Why**: Passwords were previously required to be at least 8 characters
in length. That was changed to 9 characters and then eventually to 12.
This commit updates the help docs to reflect the latest requirements.
=> Update help text to specify correct password length

_config.yml, _plugins/baseurl.rb
**Why**: When Federalist is building the site, it sets the baseurl value
to nil if the site is being build with a custom domain, meaning it is
being built to be deployed to either preview.login.gov or login.gov.
This creates a problem with the multiple languages plugin which expects
the baseurl to be present. This commit adds a plugin with a hook to set
the baseurl to an empty string if it is nil, which fixes the bug.
=> Set the baseurl to empty string by default

Gemfile
**Why**: CI will steadily upgrade the ruby version we use. This means we
don't have to upgrade the ruby version every time circle does.
=> Don't specify specific version in Gemfile

_i18n/es.yml, _i18n/fr.yml
**Why**: These translations will fallback to english by default and
having them gums up the works when trying to identify untranslated
strings.
=> Delete english from french and spanish translations

_help/index.md, _i18n/en.yml, _i18n/es.yml, _i18n/fr.yml
Dan from USAJOBS reached out saying we have a few places on the site where we list USAJOBS incorrectly. I went through and update the places where we don't have USAJOBS in all caps.
=> Changing any reference to USAJobs to USAJOBS

yarn.lock
**Why**: Event stream 3.3.6 was unpublished causing installation to fail
=> Downgrade event stream to 3.3.5

README.md
Adds the release process to the README instead of keeping it in the Wiki that isn't necessarily up to date or checked by anyone.
=> add release process to README

_i18n/en.yml, _i18n/es.yml, _i18n/fr.yml
**Why**: Per @rspeidel, the statement is overly broad given that if a
phone number is used for identity verification we may share it with a
service provider if the service provider requests it.
=> Remove sentence about sharing phone numbers

README.md
We're now building production off of the `master` branch instead of `production` – this updates the docs accordingly.
=> Remove old publishing workflow from README

_i18n/en.yml
We found a few help pages that still had hello@login.gov. Replaced it with link to the contact form.
=> Removing hello@login.gov references

_help/index.md, assets/img/security-key-light.svg
**Why**: So that the security key item has an icon
Screenshot:
=> LG-1305 Add an icon for security keys to the FAQ index

.well-known/security.txt, _config.yml
Security.txt is a proposed standard for publishing methods of reporting
and points of contact for receiving notice of security issues.
https://securitytxt.org/
It will be visible at https://login.gov/.well-known/security.txt
=> Add a security.txt file.

_i18n/en.yml
**Why**: Looks like a botched merge from #321 blew away some of the help content. This PR puts it back.
=> Revert changes to en.yml that broke the help section

_sass/components/_dropdown.scss
Adding `white-space: nowrap` to the navigation dropdown UL prevents the text from breaking to a new line on each word and creating difficult to read dropdown menus.
=> add nowrap to navigation dropdown

package.json, yarn.lock
**Why?**:  to ensure that we have all security fixes in use.
=> Update jQuery to latest, v3.4.1

_includes/contact_form.html
**Why**: So @amirbey does not have to send us angry emails about jQuery being out of date
It looks like the issue is that the form the contact center sent us included a link to the jQuery. We changed their code to not use it, but retained the jQuery import and that is what is getting picked up in GSAIT's scans. This commit removes it entirely.
=> Remove jQuery from the contact center form

_i18n/en.yml, spec/_pages/help.md_spec.rb
Spanish and French translations had the correct link already
=> Fix broken link in FAQ to authenticator (LG-2521)

_config.yml, _help/authentication-methods/which-authentication-method-should-i-use.md, _help/index.md, _i18n/en.yml, _i18n/es.yml, _i18n/fr.yml, _sass/components/_footer.scss, _sass/components/_header.scss, assets/stylesheets/main.scss, package.json, yarn.lock
WHY:
As a user who is signing up, I want to understand why certain MFA methods are recommended, so that I can make an informed decision about which one to choose
https://cm-jira.usa.gov/browse/LG-2499
AC: There is an FAQ answer on why WebAuthn is recommended
AC: There is an FAQ answer on why TOTP is recommended
AC: There is an FAQ answer on why backup codes are not recommended
Preview available here:
https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/identity-site/LG-2499_Add_FAQ_on_recommended_MFA_methods/
=> Add FAQ on recommended MFA methods

Gemfile, Gemfile.lock, _config.yml, spec/sitemap.xml_spec.rb
**Why:** we need a sitemap for search.gov
The jekyll-sitemap gem should generate a sitemap that will live at login.gov/sitemap.xml and also be indicated at login.gov/robots.txt
=> LG-2609 Add sitemap

README.md
**Why:** Apparently we don't do the old release process anymore, and master deploys right to production. Updated so the README reflects that
=> Update README to remove out of date release process

_i18n/en.yml, _i18n/es.yml, _i18n/fr.yml, yarn.lock
**Why:** As a user, I want the authentication methods FAQ on login.gov to be easy to read and accessible, so that I can understand the information given. 
[Preview for this PR](https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.app.cloud.gov/preview/18f/identity-site/nng-lg-2607-add-styles-faq-auth/help/authentication-methods/which-authentication-method-should-i-use/) vs. [the current page being updated](https://www.login.gov/help/authentication-methods/which-authentication-method-should-i-use/)
**AC**
1. A subheading style is created
2. Spacing / margins are added to give sections a breathing room between
3. The page functionally makes sense with keyboard accessibility / screen reader when tabbing through headings / element
4. `en.yml`, `es.yml`, and `fr.yml` have new styles across …
=> LG-2607 - Add new styles to FAQ

_i18n/en.yml, _i18n/es.yml, _i18n/fr.yml, _includes/contact_form.html
**Why:** The impact of TTP on Contact Center has decreased, so we are good to remove the temporary alert banner via #357 
View [Federalist preview](https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.app.cloud.gov/preview/18f/identity-site/Remove-alert-banner-for-TTP/contact/)
**How:**
1. Comment out alert banner component via ``, keeping this component intact when we need it again in the future while removing its visibility
2. Remove reference to TTP in `en.yml`, `es.yml` and `fr.yml`
=> Remove the temporary alert banner re: TTP on contact form

_i18n/en.yml, _i18n/es.yml, _i18n/fr.yml, _includes/contact_form.html
**Why:** Mailing partner is suspending operations due to the spread of COVID-19. This means that we may have a few people who proofed by mail who will not receive a letter and any mailings received after yesterday (3/16) will not be processed.
[Preview of alert banner on contact form](https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.app.cloud.gov/preview/18f/identity-site/nng-alert-banner-mailing/contact/)
**How:**
- Create an alert banner on contact form
- Redirect those who are affected to RRB contact form for questions/concerns
Note: Set a reminder to remove the alert banner when mailing partner is active again.
=> Add RRB alert banner and content for en/es/fr.yml

_includes/covid_banner.html, _pages/index.md, _pages/partners/index.md, _pages/partners/learn.md, _pages/partners/our-agency-partners.md, _pages/partners/why-login-gov.md
Adds the following banner to the homepage and all /partners pages.
=> Adds covid-19 informational banner

_i18n/en.yml, _i18n/es.yml, _i18n/fr.yml, _includes/header.html
**Why:** In the near future, we want only one Call-to-Action (CTA) link in the header instead of two (Create an account | Sign in) — Per conversations w/ @amoose, @karlaturcios and design huddle
**Note:** This is a temporary fix until we develop a more through design for 'Sign in' CTA
[Preview via Federalist](https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.app.cloud.gov/preview/18f/identity-site/nng-remove-create-an-account-link/)
**How:**
- Remove 'Create an account' code snippet
- Bold 'Sign in' so it doesn't get lost in the header/nav
=> Remove 'Create an account' secondary link

_pages/index.md
**Why**
Too many folks think the partner inquiry form is for users to setup a login.gov account :(
=> Removes covid banner from homepage

_pages/partners/index.md, _pages/partners/our-agency-partners.md, _pages/partners/why-login-gov.md
WHY
removing banner from other covid pages
=> remove covid banner from remaining  pages

_i18n/en.yml, _i18n/es.yml, _i18n/fr.yml, _includes/contact_form.html
**Why:** Login.gov is able to send out the letters now and per RRB request, we're taking the banner down (Related note: banner addition was prompted by #363).
[Preview via Federalist re: contact page](https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.app.cloud.gov/preview/18f/identity-site/nng-remove-gpo-banner/contact/)
**How:**
- Remove banner code snippet
- Remove i18n content related to RRB
=> Remove GPO banner and i18n content

_includes/header.html, _sass/components/_nav.scss
**Why**: LG-2963
**Why**: The UI to navigate to secure.login.gov was inconsistent
**How**: Reduced markup to span > a for better accessibility
**How**: Revised CSS
=> Make sign-in UI consistent (IE11 rendered poorly)

_sass/components/_nav.scss
**Why**: To base the width off the link's text instead
**How**: CSS
This is related to https://cm-jira.usa.gov/browse/LG-2963
=> Removed fixed wdith from login.gov launch widget

_i18n/en.yml
I added a section to the existing policies page, but this can be moved and changed any way you see fit.   The only requirements are that we address the following items:
-	Service name and description
-	“Message and data rates may apply”
-	Message frequency
-	Customer care information
-	Opt-out instructions
-	Link to Privacy Policy
-	“Carriers are not liable for delayed or undelivered messages”
=> Add messaging terms and conditions

.circleci/config.yml, OLD_URLS.yml, _help/changing-settings/change-my-email-address.md, _help/changing-settings/change-my-password.md, scripts/sitemap-check
**Why**: This makes sure we don't break links accidentally by making
sure that each URL in the current sitemap still points to a page
(or a redirect)
This is for #410
=> Check that we don't break links in to our site

Makefile.server
**Why**: Without defining prerequisite build targets, it's possible for a race condition to occur where Jekyll build creates the `_site` directory before CSS and JavaScript files are built, resulting in an outcome where there is no stylesheet or script files present for the site to load.
**Story**: As a developer, I can run the setup instructions, so that I can navigate to http://localhost:4000/ and see a running copy of the identity site.
It was my experience in running the setup instructions that the site appeared without any styles. It's likely not quite so obvious after the first run, since the built file will already exist. Technically the problem can still manifest after the first run, if the developer modifies files while the watch process is not running in the background, since …
=> Build CSS and JS as prerequisite for Jekyll

_config.yml, _includes/hubbot.html, _layouts/partners.html
Addresses LG-3215
* Removes hubbot Javascript include file and references
* Removes `partners` specific layout
Tested good locally.
=> LG-3215 Deactivate hubbot

.gitignore
**Why**: We upgraded jekyll via snyk. As part of that upgrade we were supposed to start ignoring this file.
=> Add the Jekyll cache to the gitignore

_i18n/en.yml, _i18n/es.yml, _i18n/fr.yml, _includes/contact_form.html
Adds a dropdown, still waiting on confirmation from our SF team that the backend is good to go
I made a separate branch with some preview configs:
- [git diff](https://github.com/18F/identity-site/compare/margolis-contact-dropdown-sba...margolis-contact-dropdown-sba-preview)
- [federalist preview](https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.app.cloud.gov/preview/18f/identity-site/margolis-contact-dropdown-sba/contact/)
=> Add contact dropdown option for SBA Connect (LG-3220)

scripts/htmlproofer-external
Treats login.gov URLs with a domain as local URLs for testing
This is a PR to patch #438 to simplify the checks and get the build passing
=> Update proofer script for external URLs

_includes/policy_nav.html, _sass/pages/_policy.scss
Before, the active page's nav link had no border:
Now:
=> Restore border on nav link of active policy page

_i18n/en.yml, _i18n/es.yml, _i18n/fr.yml, _pages/index.md
**Why:** To refine content on the [demo.login.gov](https://demo.login.gov)
😎 👉  [Federalist preview](https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.app.cloud.gov/preview/18f/identity-site/nng-lg-3628-refinement/)  
**Homepage**
**What is login.gov?**
**Translations**
=> LG-3628: Brochure site refinement

_i18n/en.yml, _i18n/es.yml, _i18n/fr.yml, _includes/banner.html, _includes/covid_banner.html, _sass/components/_header.scss
**Why:** The COVID banner will be moving to [partners.login.gov](https://partners.login.gov/).
😎  👉   [Federalist preview](https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.app.cloud.gov/preview/18f/identity-site/nng-lg-3627-remove-covid-banner/) 
**How:**
=> LG-3627: Remove COVID banner from the demo site

_i18n/en.yml, _i18n/es.yml, _i18n/fr.yml
**Why:** To fix headings that skip level on both homepage and 'What is login.gov' pages
😎 👉  [Federalist preview](https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.app.cloud.gov/preview/18f/identity-site/nng-lg-3000-a11y-fixes-semantic/)
**How:** This PR will be merged to `demo`, not `master`
- **Homepage:**
- Correct `h4` to `h3` headings for 'Individuals', 'Agency partners', and 'Agency developers'
- Update en/es/fr.yml files
- **What is login.gov:** 
- Correct `h4` to `h3` headings for 'Login.gov is trusted by'
- Update en/es/fr.yml files
**AC:**
=> LG-3000: Fix headings

_layouts/base.html, _layouts/main.html, _layouts/not_found.html, spec/_pages/404.html_spec.rb
I found one discrepancy between the login.gov Google Analytics and the DAP analytics: the 404 page did not have DAP, so this fixes that
=> Make sure DAP is included on 404 page (LG-3629)

_pages/create_an_account.md, _pages/who_uses_login.md, _sass/components/_list.scss, _sass/pages/_create_an_account.scss
The language dropdown currently looks like this:
But it should look like:
The list styling was meant for the Create an Account page. Made the css more specific.
=> Fix spacing on the language dropdown

.babelrc, .gitignore, package-lock.json, package.json, webpack.config.js
**Why**: Preempt potential incompatibilities and future maintenance burden.
As part of LG-3849, I had noticed some Babel errors in introducing Jest (configures [`babel-jest`](https://www.npmjs.com/package/babel-jest) by default) I'm hopeful could be resolved by upgrading.
=> Upgrade Webpack, Babel dependencies

Makefile.server
**Why**: Webpack run in watch mode will already perform an initial build. Without these changes, two Webpack builds occur when running `make run`.
Only difference would be if someone were to run `make jekyll` directly, it will no longer build JavaScript. It doesn't appear we run or recommend this, nor does it seem "expected" that a Jekyll task would build JavaScript.
=> Deduplicate Webpack build in `make run`

package-lock.json, package.json
**Why**: Fewer dependencies to maintain. Avoid confusion about source of normalize.css.
These dependencies are not used in source.
In the case of `hint.css`, you can also check for references to `hint--`-prefixed classes ([documentation](https://www.npmjs.com/package/hint.css#get-started)).
Normalize.css is still included, but not directly referenced, and instead inherited through USWDS [[1]](https://github.com/uswds/uswds/blob/b0e7ea3800e5bb5960e0925716cf5363375ee613/config/gulp/sass.js#L60-L61) [[2]](https://github.com/uswds/uswds/blob/3dc296ec56cd621fe52d918701fd94621d96a198/src/stylesheets/packages/_global.scss#L3).
You can confirm it's still included in the output `_site/assets/css/main.css`:
```
make build && cat _site/assets/css/main.css | grep -q normalize.css && echo "Found" || …
```
=> Remove unused CSS dependencies

_includes/meta.html
Adds the following to all pages to allow synthetic monitors to have static text to look for:
~~~
<meta sys-status=”login.gov site up and running”>
~~~
This is needed to ensure the switch from old to new brochure site does not result in false alarms from NewRelic Synthetics.
=> Add sys-status meta tag for current brochure site

_includes/meta.html
Adds the following to all pages to allow synthetic monitors to have static text to look for:
~~~
<meta sys-status=”login.gov site up and running”>
~~~
This is needed to ensure the switch from old to new brochure site does not result in false alarms from NewRelic Synthetics.
=> Add sys-status meta tag for new brochure site

_includes/header.html, _sass/components/_nav.scss, assets/js/main.js
**Why**:
- Less code to maintain
- Rely on mature, battle-tested offering from USWDS
- Fix issue where text and images appeared vibrantly through the overlay
- Fix issue where background color was incorrect per design:
- Was 50% `#000000`
- Should be 50% `#454545` ("base-darker").
Before|After
---|---
=> Replace custom mobile menu overlay with USWDS

.gitignore, Makefile.server, README.md, _config.dev.yml
**Why**: As a developer, I don't want to sit and wait 10 seconds after I save a file to be able to see my changes reflected on the page, so that I'm not wasting time.
**Implementation Notes:**
Disabling translations is a bit of a sticky point, considering that...
- We will want to be able to test non-English locales
- The current language picker does not render correctly / at all when only English is available as an option
The proposed implementation seeks to try to find a balance here where the options are still included in the base configuration as an example of how to re-enable them for development testing.
_Ideally_, the build performance of multiple languages would be fast enough that we could always build all locales.
=> Improve local development rebuild performance

_includes/help/nav_sidenav.html
**Why**: Avoid invalid values being assigned as attributes, where capture will capture with whitespace included.
```
Expected the HTML found at $('.usa-parent') to have no violations:
<li class="usa-sidenav__item usa-parent usa-current" aria-expanded="
true
">
Trouble signing in?
</li>
Received:
"ARIA attributes must conform to valid values (aria-valid-attr-value)"
Fix all of the following:
Invalid ARIA attribute value: aria-expanded="
true
"
You can find more information on this issue here: 
https://dequeuniversity.com/rules/axe/4.1/aria-valid-attr-value?application=axe-puppeteer
```
=> Assign sidenav ARIA attributes as trimmed strings

_pages/contact.md
**Why**:
- Consistency with Help layout
- Navigation is not tangential to content per purpose of aside
- Navigation itself is still semantically represented using `<nav>`
Related Slack conversation: https://gsa-tts.slack.com/archives/C01710KMYUB/p1608671237404800?thread_ts=1608670099.403700&cid=C01710KMYUB
=> Render Contact Us side navigation as div

_includes/help/nav_sidenav.html
**Why**: So that users who navigate by page landmarks can distinguish between multiple landmarks of the same role.
```
Expected the HTML found at $('.margin-y-4') to have no violations:
<nav class="margin-y-4 sidenav">
Received:
"Ensures landmarks are unique (landmark-unique)"
Fix any of the following:
The landmark must have a unique aria-label, aria-labelledby, or title to make landmarks distinguishable
You can find more information on this issue here: 
https://dequeuniversity.com/rules/axe/4.1/landmark-unique?application=axe-puppeteer
```
Reuses implementation from Contact Us page navigation (#486).
=> Add accessible label for help side navigation

_includes/contact_form.html
**Why**: Mistakenly removed in #486 as it was not understood to be a honeypot field. Honeypots are a hardening measure to prevent spam from some spam bots.
See: https://help.salesforce.com/articleView?id=pardot_forms_add_honeypot.htm
See: #338
Improvements have been made to address usability and accessibility issues:
- The field is no longer focusable by users navigating the page using a keyboard
- The field is no longer exposed to assistive technology
=> Restore (and improve) honeypot field to demo site contact form

_i18n/en.yml, _i18n/es.yml, _i18n/fr.yml, _includes/banner.html, _sass/_colors.scss, _sass/components/_usa-banner.scss, _sass/components/all.scss
**Why:** Update text to reflect the latest USWDS banner component per [guidance](https://designsystem.digital.gov/whats-new/updates/2020/09/08/Improvements-banner/).
👉🏼  [Federalist preview](https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.app.cloud.gov/preview/18f/identity-site/nng-lg-3493-uswds-usa-banner/)
**How:** This will be merged into `demo`
1. Update text for all EN/ES/FR languages. (Note: ES text is pulled from USWDS while FR is pulled from Google Translate)
2. Correct alignment (See before/after screenshots below)
3. Add `role="img"` and `aria-hidden="true"` (Also, making `alt=""` blank since the graphics are decorative)
**Questions:**
1. **French translation:** How should we get a better French translation? Currently, it's from Google Translate
2. **Lock pad icon:** In …
=> LG-3493: Update `usa-banner` with the new USWDS component

_includes/help/nav_sidenav.html, _sass/components/_nav-sidenav.scss
**Why**: `div` or `ul` are not valid child elements of `ul`.
Reference: https://designsystem.digital.gov/components/sidenav/
```
Expected the HTML found at $('.usa-sidenav') to have no violations:
<ul class="usa-accordion usa-sidenav">
Received:
"<ul> and <ol> must only directly contain <li>, <script> or <template> elements (list)"
Fix all of the following:
List element has direct children that are not allowed inside <li> elements
You can find more information on this issue here:
https://dequeuniversity.com/rules/axe/4.1/list?application=axe-puppeteer
```
=> Render help sidenav subnavigation as nested list

_i18n/en.yml, _i18n/es.yml, _i18n/fr.yml, _pages/policy/security.md, _pages/security.md
**Why**: Previously there was a "Security" standalone top-level page. This appears to have been removed in the redesign. The changes here propose to redirect the page to /policy/security instead.
Related Slack discussion: https://gsa-tts.slack.com/archives/C01710KMYUB/p1609258661431900
```
Expected the HTML found at $('html') to have no violations:
<html lang="en">
Received:
"Page must contain a level-one heading (page-has-heading-one)"
Fix all of the following:
Page must have a level-one heading
You can find more information on this issue here:
https://dequeuniversity.com/rules/axe/4.1/page-has-heading-one?application=axe-puppeteer
```
=> Redirect security top-level URL to policy subpage

_includes/banner.html, _sass/components/_header.scss
**Why**: Resolve invalid nested header while assuring only single banner on page.
See: https://github.com/18F/identity-site/pull/494/files#r549832708
>Only discovered after rebasing the merged changes into my end-to-end testing branch at #469: This is a bit of a problem in that the banner partial is nested into a `<header>` element:
>
>https://github.com/18F/identity-site/blob/42f73f91352d230db072d128835bcff611975b70/_layouts/main.html#L9-L15
>
>Nesting `<header>` is not valid HTML ([see validator result](https://validator.w3.org/nu/?doc=https%3A%2F%2Fdemo.login.gov%2Fwho-uses-login%2F)).
>
>It's also an interesting challenge to resolve this while respecting a few other guidelines around landmarks:
>
>- https://dequeuniversity.com/rules/axe/4.1/region
>- …
=> Revert banner header to div

_includes/one_account_banner.html, _layouts/main.html, _pages/create_an_account.md, _pages/index.md, _pages/who_uses_login.md, _sass/components/_one-account-banner.scss
**Why**: Resolves issue where aside contained in main element is flagged as violation of guidelines.
Rather than change element from `aside` to `div`, treat as proper accompanying complementary content to main content by extracting as sibling to `main`, aligning with intent of the guideline.
```
Expected the HTML found at $('.banner') to have no violations:
<aside class="banner tagline-content">
<header class="tagline">Your one account for government</header>
<p><a class="learn-account-creation usa-button usa-button--big" href="https://secure.login.gov/sign_up/enter_email">Create an account</a></p>
</aside>
Received:
"Aside must not be contained in another landmark …
```
=> Extract "One Account" banner to adjacent aside top-level element

_layouts/base.html, _layouts/help_landing.html, _layouts/main.html
**Why**: Cleanup. Lingering remnants of removed Bootstrap scrollspy behavior.
See: 6c97a118044299e3427edfb002b66e5ac816aa7b
=> Remove unused scrollspy attributes

README.md, _help/README.md
Since Help is structured differently from the rest of the site, give future developers a heads-up on maintenance.
=> Add readme to Help sections

Gemfile, Gemfile.lock, _config.yml
**Why**:
- Required by USWDS
- See: https://github.com/uswds/uswds#sass-compilation-requirements
- Prerequisite to fix visual defect of search fields in iOS (rounded corners)
- Discovered in course of compiling screenshots for design approval of #511
=> Configure autoprefixer for Jekyll

_i18n/en.yml, _i18n/es.yml, _i18n/fr.yml, _includes/contact_form.html, _includes/footer.html, _includes/language_search.html, _pages/contact.md
**Why**: As a French or Spanish visitor to login.gov, I want to be able to read and submit a contact form submission in my native language, so that I have the most likelihood of resolving my issue.
**Live Preview:** https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.app.cloud.gov/preview/18f/identity-site/aduth-contact-us-translations/contact/
**Questions:**
- @nickttng The given content from the ticket LG-3980 is not organized as per the design implemented in LG-3496. Can you please advise if the current layout needs adjustment? For example, the "Partner with login.gov" and "Report a security issue" (now "Report an issue") sections were previously displayed below the form.
- @Danielle-Lee Noting a couple strings for which translations were not available. Currently I've used Google …
=> LG-3980: Add translations for Contact Us page

_config.yml, _help/specific-agencies/overview.md, _help/specific-agencies/sam.md, _help/specific-agencies/trusted-traveler-programs.md, _help/specific-agencies/usajobs.md, _i18n/en.yml, _i18n/es.yml, _i18n/fr.yml, _pages/help.md
- Only English translations for now
[Preview Link](https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.app.cloud.gov/preview/18f/identity-site/margolis-specific-agencies-help/help/specific-agencies/overview/)
Wanted to highlight a few visual quirks thanks to our `:first-of-type` rules. Since there's no custom markup on these, my inclination is to leave them as-is and we can clean up list styles in a separate PR?
| page | screenshot |
| --- | --- |
| [Overview Page][overview] | <img src="https://user-images.githubusercontent.com/458784/103950886-8a728200-50f2-11eb-8fda-cccccc3276c8.png" width=200 /> |
| [SAM page][sam] | <img src="https://user-images.githubusercontent.com/458784/103950890-8e060900-50f2-11eb-827e-5534c432e8f1.png" width=200 /> |
[overview]: …
=> Add "Help with specific agencies" section (LG-3565)

spec/e2e/accessibility_spec.js
**Why**: As of #512, the Privacy layout is no longer broken and passes accessibility scan.
=> Include policy pages in accessibility test

_i18n/en.yml, _i18n/es.yml, _i18n/fr.yml, _layouts/sidenav.html, assets/js/main.js
Because links were fully-qualified, they were not detected by the smooth scroll selector. Change links to hash fragments, which previously did not work only because in non-English locales, prepending base URL would cause hash to resolve from root. Avoid prepending by assigning nav URL as locale-specific.
=> LG-4008: Fix smooth scroll for sidenav layouts

Makefile.server
**Why**: Avoid minifying output in development environment for easier debugging.
Support already available in our Webpack configuration:
https://github.com/18F/identity-site/blob/72bf40df6911041a54deac66564f61aa230ce78c/webpack.config.js#L1
=> Run Webpack in development mode when using `make run`

_includes/one_account_banner.html, _sass/components/_one-account-banner.scss
Previously, the "Your One Account" banner was explicitly hidden on smaller viewports. With this pull request, it is now shown on all viewport sizes. The styles have been updated to support his, per design guidance from @nickttng (see ticket for Figma design document). The backdrop opacity was also reduced from 100% to 90% per the original design document.
**Live Preview:** https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.app.cloud.gov/preview/18f/identity-site/aduth-lg-4019-one-account-mobile/
**Screenshots:**
&nbsp;|Desktop|Mobile
---|---|---
Create Account|![image](https://user-images.githubusercontent.com/1779930/104055609-0cc77880-51bd-11eb-8b3f-d4f4653402a5.png)|![image](https://user-images.githubusercontent.com/1779930/104055596-0802c480-51bd-11eb-901d-aa3cf6507a24.png) …
=> LG-4019: Show and scale "One Account" banner for mobile

_pages/index.md
**Why**: Mistakenly lost as part of merge conflict resolution between be97397982c0185249f75d4a186bb13aa2e1ce79 and 0e4da8621dad9280e8819d62a9966913824b1256.
=> Restore "Your One Account" banner to homepage

_sass/components/_layout.scss
Resolves an issue where...
- in Safari on iOS
- in mobile navigations where content is lengthy (e.g. Help section with expanded subsections)
...the display of the search field in mobile navigation would shrink unexpectedly.
See: https://github.com/uswds/uswds/pull/3932
Before|After
---|---
=> Fix spacing of search field in mobile navigation

_pages/what_is_login.md, _sass/components/_list.scss, _sass/pages/_home.scss, _sass/pages/_what_is_login.scss, _sass/pages/_who_uses_login.scss
Related: LG-3768
**Why**: Link styles are not automatically applied globally and must be explicitly opted into, else the links will be styled with browser-default styling, using a color which does not conform to login.gov Design System expectations.
In the brochure site, this is often resolved by wrapping content with `page-content__prose` class, or at least sprinkling `usa-link-style` USWDS mixin in container classes where links are expected.
For proposed separate consideration: Applied link colors use default color for Login Design System links, which does not always match design, and is not always consistent with links in each page (e.g. home page links are `#0071bb`, and help center links are `#205493`). Either LGDS theme variable assignment for link colors should be adjusted, or LGDS …
=> LG-3963: Add missing link styles

_sass/components/_nav.scss
**Why**: Focus should always be visible.
See: https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-focus-visible.html
**Implementation notes:**
Focus styling would normally be present, but since it relies on `box-shadow`, and the `.sign-in-logo` button styling applies custom `box-shadow`, it overrides. Restore by re-applying focus style with more specific selector in `:focus` state.
**Screenshot:**
=> LG-4021: Add focus styling to "Sign in with login.gov" button

_sass/components/_list.scss
Honestly, I'm surprised this works 😬 
Based on the PIV/CAC bullet, it appears this wraps correctly across multiple lines as well
| --- | --- |
| <img width="775" alt="Screen Shot 2021-01-11 at 9 42 58 AM" src="https://user-images.githubusercontent.com/458784/104218470-a0818a80-53f1-11eb-8fbd-a688290e2355.png"> | <img width="775" alt="Screen Shot 2021-01-11 at 9 43 52 AM" src="https://user-images.githubusercontent.com/458784/104218463-9eb7c700-53f1-11eb-981c-8c7aa9a800e4.png"> |
=> Add spacing after nested list bullets

_layouts/help_landing.html, _layouts/main.html
**Why**: Demo banner should not be shown on live site. Federalist allows per-environment site configuration values. It would be assumed that this change would be paired with adding `demo_banner: true` as a site configuration for demo and preview branch environments.
https://federalist.18f.gov/documentation/#advanced-settings
=> Conditionally display demo site banner by site configuration

_sass/components/_hero.scss
**Why:** Improve how hero images are displayed (See before and after screenshots below). 
IIRC, this PR is not part of any ticket, but it's a quick fix that I want to address recently (CC @shawnique @akhlaqkhan)
**How:** Configure `background-position` and `background-size`
- Reduce size for _What is login.gov?_ hero image to create more spacing between the hero image and the "— and"
- Reposition and resize _Create an account_ hero image so it doesn't appear unanchored
=> Resize hero images

_i18n/en.yml, _i18n/es.yml, _i18n/fr.yml, _includes/contact_form.html, _sass/components/_form.scss
**Why**: As a member of public, I should be able to identify what fields are optional when filling in Contact form for login.gov so that I can submit the form intuitively with minimum friction and time.
**References:**:
- https://designsystem.digital.gov/components/form-templates/#name-form
**Screenshot:**
=> LG-4027: Add "Optional" label for optional contact form fields

_pages/help.md
**Why:** Per #547, we are removing content about USAJOBS. So, this PR removes the reference about the USAJOBS from the Help Center landing page
**Note:** We don't have Spanish and French translations yet for the landing page, so we will need to revisit this issue in the future. //cc @shawnique @akhlaqkhan
=> Remove `USAJOBS` reference from Help landing page

_i18n/en.yml, _i18n/es.yml, _i18n/fr.yml, _pages/help.md
As a user, I should see help page information in my language (Spanish or French). 
AC:
* Text is translated.
* Links go to translated pages.
=> Translate help landing page

_includes/header.html
**Why**: As a user navigating the site in Spanish, I expect that clicking "¿Qué es login.gov?" in the top-level navigation brings me to the Spanish-translated "What is login.gov?" page, so that I can access the content in my preferred language.
=> Fix top-level navigation dropping locale preference

spec/e2e/accessibility_spec.js
**Why**: Because issues have been resolved, and the tests pass. We want as few (ideally zero) exceptions in these tests as possible.
=> Opt-in Partners section for accessibility scan

_sass/components/_btn.scss, _sass/components/_header.scss, _sass/components/_nav.scss
**Why:** To transition from Source Sans Pro to Public Sans
😎 _/¯ [Preview](https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.app.cloud.gov/preview/18f/identity-site/nng-lg-4142-replace-source-sans/)
**Context:** After the soft launch, there are leftover components and elements that still use Source Sans Pro. However, the Login Design System hasn't yet made a transition to Public Sans. For this reason, the issue is to individually target components and elements. After the design system update, we will remove `font-family` once we assign `$theme-font-sans` design system variable to Public Sans.
**What has been updated:** See below for a comparison between the two font families
- `usa-banner` component
- Language options button
- Sign-in button
- Navbar - desktop
- Mobile/tablet menu …
=> LG-4142: Update leftover Source Sans to Public Sans 

_sass/components/_card.scss, _sass/components/_hero.scss, _sass/components/_list.scss, _sass/components/_typography.scss, _sass/pages/_who_uses_login.scss
**Why:** Several pages are inconsistent with font-size and line-height, both paragraph and/or list:
- [Who uses login.gov](https://www.login.gov/who-uses-login/)
- [Create an account](https://www.login.gov/create-an-account/)
- [Help center](https://www.login.gov/help/)
- [Privacy & security](https://www.login.gov/policy/) and related pages
👉🏼  [Preview](https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.app.cloud.gov/preview/18f/identity-site/nng-lg-3979-public-sans-updates/)
**How:**
- Update any font-size inconsistencies to 16px
- Update any line-height inconsistencies to 30px / 1.875rem
- Update list-style-type dash `⁃` for nested list
- **Misc:** Set/increase line-height for hero descriptions (they gotta breathe)
=> LG-3979: Typography updates

_includes/help/nav_sidenav.html, _sass/components/_site.scss
As a product owner, I want sticky navigation on the help center pages so that there is consistency with other side navigation menus.
=> make help navigation sticky

_pages/404.md
When manually testing the 404 page, I found that clicking the logo would lead to a 404 as the `href` attribute was missing. This is an attempt to fix that bug.
=> fix href attribute

admin/config.yml
This PR fixes the layout problem that would happen when english landing pages are created. Before, you would see no content on an english landing page despite it being created from the landing page collection. Now, the expected behavior of english landing pages having the correct layout shows up.
=> Fix English landing page layout

_includes/header--help.html
**Why**: In transitioning to Netlify CMS, we no longer track articles in settings data. Instead, each is a content page with a category corresponding to the help category it is associated with. Just like we do with sidenav rendering, we should filter pages to construct the mobile primary navigation.
Before these changes, additional menu items aren't shown when a user taps on a mobile menu item in the help section.
See: https://github.com/18F/identity-site/pull/596/files#diff-f73e2a71b0a1bd48fbf42480e81c5a7f1b0f846eac2b83cad53644201db1c5aa
Before|After
---|---
=> Fix help section mobile primary menu subitem rendering

_data/fr/settings.yml
This PR addresses missing translations for the footer in French. 
Below is the current state of the footer as seen on login.gov
Below is the state of the footer that we are seeking to achieve
=> LG-4685: Translate footer text to French

_includes/language_picker.html, spec/all_pages_spec.rb, spec/spec_helper.rb, spec/support/matchers.rb
**Why**: As a user, I expect that when I'm reading the French or Spanish version of the site, links within content maintain the locale, so that I can follow navigation in my preferred language.
Also incorporates LG-4388: "Brochure Site: Add "lang" attribute to language dropdown items", as an indicator of exception for language picker links.
This is expected to fail build currently, since there are a number of existing issues.
=> LG-4684: Add spec to verify localized pages maintain locale in links

scripts/sitemap-check, spec/all_pages_spec.rb, spec/support/matchers.rb
See: https://github.com/18F/identity-site/pull/657#discussion_r649484068
We use htmlproofer, which already checks for valid links, so this spec is redundant. It's also currently skipped.
=> Remove valid internal pages spec

_includes/scripts.html
This ticket adds the integrity attribute to the Touchpoints script tag. This was done in hopes of adding a security layer to responses on the Touchpoints survey.
=> add integrity hash to touchpoints script tag

package-lock.json, package.json
This PR upgrades Puppeteer from version 5.5.0 to 10.0.0. This upgrade is an attempt to fix flaky tests in the CI pipeline.
=> upgrade puppeteer 5.5.0 -> 10.0.0

_data/en/settings.yml, _data/es/settings.yml, _data/fr/settings.yml, _includes/header--help.html, _includes/header.html, spec/i18n_spec.rb
**Why**: Per test case description, there should be no missing translations, so the missing translation set should be empty.
It's expected that this will fail, and was only passing previously because there currently are missing translations. Some of these are being fixed in #665.
=> Update i18n spec to assert no missing translations

_sass/components/_site.scss, assets/js/main.js
**Why**:
- Standard browser behavior which exists specifically for this purpose, and is likely to be more performant and less error-prone.
- Fixes an issue where focus on the heading is delayed by the animation, and avoids needing to make the non-interactive heading focusable.
- Fixes an issue where focus events on the link target are never removed and can be applied multiple times.
- Fewer dependencies on jQuery, toward eventual removal.
See: https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior
Technically this removes smooth scroll support for Internet Explorer, though it seems reasonable as a [progressive enhancement](https://en.wikipedia.org/wiki/Progressive_enhancement) functionality.
=> Implement smooth scroll via CSS

assets/js/main.js
**Why**: Since the script is the last content of the page, all elements referenced in the scripts will already be present. It's unnecessary to wait for the DOMContentLoaded event, which may introduce a brief delay. Additionally, this removes the domready dependency and reduces dependency on jQuery, facilitating its removal in the future.
For review, it's easiest to select the GitHub option "Ignore whitespace changes".
=> Run JavaScript immediately on load

Makefile.server
**Why**: So that I can trust that when I save while running `make run`, the site contents will be rebuilt.
Incremental flag seems very flakey, and seems to depend heavily on the type of content being saved whether it actually works (e.g. markdown vs. partials, etc).
=> Stop using incremental Jekyll build

spec/e2e/accessibility_spec.js
Context: https://github.com/18F/identity-site/pull/674#issuecomment-877332750
**Why**: Due to media query styling, some issues are only present at one or the other viewport. Previously, the viewport was quite small so desktop-specific issues were not surfaced.
Review ignoring whitespace changes: https://github.com/18F/identity-site/pull/677/files?w=1
~Note: It's expected this will fail pending the changes at #674.~
=> Test small and large viewports for accessibility tests

_config.yml, _includes/language_picker.html, _plugins/locale_url_filter.rb, spec/_plugins/locale_url_filter_spec.rb
Context: https://github.com/18F/identity-site/pull/674#discussion_r667064248
**Why**: To simplify language picker URL logic.
=> Add support for URL locale filter to target specific locale

content/_en/policy/messaging.md, content/_es/policy/messaging.md, content/_fr/policy/messaging.md
This will update the language to remove references to help@login.gov which was causing confusion to customers. This also updated the language around the rest of the sentence for all available internationalizations.
=> LG-4251 remove login gov text

_config.yml, _includes/already_have_an_account_banner.html, _includes/header--help.html, _includes/header.html, _includes/help/nav_sidenav.html, _includes/meta.html, content/_en/help/get-started/create-your-account.md, content/_en/help/get-started/overview.md, content/_en/help/trouble-signing-in/overview.md, content/_en/help/verify-your-identity/how-to-verify-your-identity.md, content/_en/landing/who_uses_login.md, content/_en/policy/contact.md, content/_es/help/get-started/create-your-account.md, content/_es/help/get-started/overview.md, content/_es/help/trouble-signing-in/overview.md, content/_es/help/verify-your-identity/how-to-verify-your-identity.md, content/_es/landing/who_uses_login.md, content/_es/policy/contact.md, content/_fr/help/get-started/create-your-account.md, content/_fr/help/get-started/overview.md, content/_fr/help/trouble-signing-in/overview.md, content/_fr/help/verify-your-identity/how-to-verify-your-identity.md, content/_fr/landing/who_uses_login.md, content/_fr/policy/contact.md, scripts/htmlproofer-external, spec/all_pages_spec.rb, spec/spec_helper.rb, spec/support/matchers.rb
**Why**: So that we ping fewer URLs and avoid pinging same-origin URLs, improving performance, reducing flakiness, and eliminating unnecessary requests to external sites.
Before:
>Checking 74 external links...
After:
>Checking 53 external links...
=> Improve external link check URL normalization

content/_en/help/verify-your-identity/how-to-verify-your-identity.md, content/_es/help/verify-your-identity/how-to-verify-your-identity.md, content/_fr/help/verify-your-identity/how-to-verify-your-identity.md
The purpose of this ticket is to add a hyperlink to the "Don't have a state issued ID?" copy on the "Verify your Identity" page. The text now links the user to the "Accepted State-Issued Identification" page.
=> LG-4051: Make "Don't have a state-issued ID?" a live link

_data/en/settings.yml, _data/es/settings.yml, _data/fr/settings.yml, _layouts/contact_us.html
**Why**: Backend was deployed without spaces around the dash
See debugging notes in Slack: https://gsa-tts.slack.com/archives/C20J64X6V/p1626798587009000?thread_ts=1626796218.008500&cid=C20J64X6V
=> Fix PBGC dropdown option

_data/en/settings.yml, _data/es/settings.yml, _data/fr/settings.yml
This pull request removes DS Logon from our contact form. Spoke with @amoose @orenyk @TiffanyAndrews and we no longer need this as a drop down option.
=> Remove DS Logon from contact us form.

spec/e2e/accessibility_spec.js
**Why**: Suspected cause of intermittent build failures attributable to nested ReCaptcha iframes.
We could be more specific with the selector here, but (a) the frame is added dynamically by Google's own JavaScript and could change over time and (b) we don't expect to have any content shown in an iframe.
=> Exclude iframes from accessibility end-to-end tests

_plugins/locale_url_filter.rb, spec/_plugins/locale_url_filter_spec.rb
**Why**: It was only necessary so long as we had translated Markdown data which used the "\_\_LOCALE_BASE_URL\_\_" magic string, which is no longer the case after #691.
=> Remove unused replace_locale_base_url filter

content/_en/landing/create_an_account.md, content/_fr/landing/create_an_account.md
The purpose of this ticket is to translate and implement password guideline text as suggested by a translation service.
Why: So that the text can be as accurate as possible in translated languages.
Note-the Spanish copy was **not** modified because the original text and the translated text were the same.
=> LG-4054: Translate and implement password guidelines text

_data/en/settings.yml, _data/es/settings.yml, _data/fr/settings.yml, _includes/contact_form.html
This pull request removes "account linking" as an option from out customer support form. As most (if not all) of these request are related to the service provider, they are now a sub-category on non Login.gov related tickets.
=> Remove account link from contact form

README.md
**Why**: So that a developer knows where to look to see the site running on their computer.
cc @peggles2
=> Add URL to README instructions

.circleci/config.yml, Makefile
**Why**: Because "npm ci" ignores and destroys the cached node_modules and is otherwise difficult to cache. "npm install" should behave similar, respect package-lock.json, hydrate from cache. The other behavior of "npm ci" of validating package-lock.json [isn't always reliable](https://github.com/18F/identity-style-guide/pull/268), and is replicated here with check-lockfiles, largely copied from similar scripts in identity-style-guide and identity-idp.
Related: https://github.com/npm/cli/issues/564
From [example build](https://app.circleci.com/pipelines/github/18F/identity-site/2056/workflows/9c3753ae-9df4-4edb-993a-47b38fc08b7e/jobs/8691):
```
Found a cache from build 8619 at v2-dependencies-gGKVNxLRg3iHjN88fQag16qWfIEt44dSLDpRuOkhS2s=
Size: 170 MiB
Cached paths:
* …
```
=> Switch from "npm ci" to "npm install" for CI

README.md
This PR adds instructions for users to develop with NetlifyCMS
**Why**: So that developers know how to develop all aspects of the repository.
=> add instructions for developing NetlifyCMS in dev

_includes/scripts.html
This PR removes the integrity hash from the Touchpoints script
Why: When the script had the integrity hash, the script would not load. The below error is what we saw after it was added
The Touchpoints team informed us that the integrity has was not needed and not the recommended practice to add the survey, therefore, we are removing the hash.
=> remove integrity hash from touchpoints survey

_includes/contact_form.html, assets/js/contact.js
**Why**: Due to the upgrade in #777, new styling for error messages now causes part of an error icon to appear when there is no error.
This is related to updated error styling introduced as part of https://github.com/18F/identity-style-guide/pull/265 .
Contact form: https://login.gov/contact/
Note that the issue can't be seen in Federalist previews, since we don't render the ReCaptcha elements there. You will need to confirm locally, where ReCaptcha is shown (with default configuration, at least).
Before|After
---|---
**Implementation notes:**
- ~Using the [`classList` API](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList) would be simpler, but it is not supported in Internet Explorer, and we don't have a (reliable) polyfill.~ **Edit:** As discussed in …
=> Fix contact form empty error message visual appearance

_layouts/sidenav.html
This pull request updates the policy left nav to highlight the active page.
=> LG-5497 - fix leftnav to highlight active page

_data/en/settings.yml, _data/es/settings.yml, _data/fr/settings.yml, _layouts/sidenav.html
The PR fixes a bug--if a user went to the Privacy and Security act statement page, the user would see the original page. If they clicked away from that page to another (ex: How does it work), the Privacy and Security link would then get the attribute of the current page they were on.
This PR makes it so that the Privacy and Security Act statement link *always* redirects to [Login.gov/policy](http://login.gov/policy)
=> Clicking side navigation parent link reloads current page

.well-known/security.txt, content/_policy/contact._en.md, content/_policy/contact._es.md, content/_policy/contact._fr.md, content/_policy/security._en.md, content/_policy/security._es.md, content/_policy/security._fr.md
The existing link pointed to an 18F page that was out of date
=> Update links to Vulnerability Disclosure Policy

_sass/components/partners/_partners.scss
Why: Fixing the overlap of the thumbs up icons on /partnerships/our-services when viewed on mobile.
=> LG-5875 Bullets overlap fix

spec/e2e/accessibility_spec.js
Because some pages insert dynamically-generated content via HubSpot scripts, the page content may not be ready by the time the accessibility tests are run, even if in reality every page would have valid content given enough time for the script to run.
=> Testing: Wait for heading before running accessibility specs

_includes/partners/header.html
- Also remove some empty span tags
- I also sentence-cased the buttons? The ticket was unclear, so I went for it.
| state | screenshot |
| --- | --- |
| before | <img width="1128" alt="Screen Shot 2022-04-06 at 3 49 27 PM" src="https://user-images.githubusercontent.com/458784/162085578-62a44edc-f9e1-40b3-8496-50292ec1d36e.png"> |
| after | <img width="1128" alt="Screen Shot 2022-04-06 at 3 49 30 PM" src="https://user-images.githubusercontent.com/458784/162085590-5093d65e-7d0b-41cb-bdf8-c5759f1c8516.png"> |
=> Use sentence case for items in partners heading (LG-6100)

_sass/components/_hero.scss
| | desktop | mobile |
|-|---|---|
| before | <img width="1037" alt="Screen Shot 2022-04-06 at 4 10 58 PM" src="https://user-images.githubusercontent.com/458784/162088310-b1574801-1019-4af2-9667-4c37d6dceb67.png"> | <img width="805" alt="Screen Shot 2022-04-06 at 4 11 12 PM" src="https://user-images.githubusercontent.com/458784/162088345-48052e76-9716-419a-90df-2d3101be8c0e.png"> |
| after | <img width="1037" alt="Screen Shot 2022-04-06 at 4 10 55 PM" src="https://user-images.githubusercontent.com/458784/162088332-8e632ad5-4084-49d4-8b46-bb49bd734fa0.png"> | <img width="805" alt="Screen Shot 2022-04-06 at 4 11 16 PM" src="https://user-images.githubusercontent.com/458784/162088365-76823996-3b16-432b-aaec-e092b4318dc5.png"> |
=> Fix partners hero text/background color at smaller break (LG-6099)

_includes/partners/header.html, _sass/pages/_partners.scss
Why? Updated the Partners logo in the header to use an image rather than image + span.
Old Logo:
New Logo:
=> Update Partners Logo in Header

_includes/partners/header.html
Fixes link to contact-us on mobile menu:
https://cm-jira.usa.gov/browse/LG-6202
=> Fix link to contact us 

spec/_pages/index.md_spec.rb
**Why**: The content doesn't exist, nor is it checked for in NewRelic.
Timeline:
- Spec added in #85
- Content changes, test skipped in #428
Per the test case message, while there is a monitor in NewRelic "prod login.gov static site monitor", it appears to currently be configured as a simple [ping monitor](https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/getting-started/types-synthetic-monitors/), not checking for specific content.
=> Remove invalid, unused page spec

_config.yml, robots.txt
**Why**: So we can merge the /partners redesign long-lived branch
and keep iterating on it before linking to it and making it live
=> Hide /partners from crawlers (LG-6391)

_includes/components/3-col.html, _includes/partners/x-col.html, content/_partners/index._en.md
This reverts commit 7db61bc8bc6a2fe6127dd8cb8bd0e2ae3145c254.
Background: 7db61bc8bc6a2fe6127dd8cb8bd0e2ae3145c254 added ` | replace: 'site.baseurl', site.baseurl ` but we also have a (`base_url.rb` plugin https://github.com/18F/identity-site/blob/main/_plugins/base_url.rb) that prefixes the base url to all links starting with `/`... so there was some duplication
This is in draft because it's hard to test locally
=> Fix links on partners homepage (LG-6320)

_sass/components/_footer.scss
Why? Fixes overlap of the login.gov partners logo in the subfooter.
Overlap was happening around 770px width.
=> LG-6288 fix partners logo overlap in subfooter

content/_partners/contact._en.md, content/_partners/rrb-impact-story._en.md, content/_partners/sba-impact-story._en.md
There are issues with a few page titles.
- [Contact us](https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.app.cloud.gov/preview/18f/identity-site/partners-redesign/partners/contact/) has `Contact._en | Login.gov` as a title
- Both [SBA](https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.app.cloud.gov/preview/18f/identity-site/partners-redesign/partners/sba-impact-story/) and [RRB](https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.app.cloud.gov/preview/18f/identity-site/partners-redesign/partners/rrb-impact-story/) impact stories share the same title, `Impact story | Login.gov`. This could be more descriptive so that users can quickly identify the content.
This PR proposes these fixes:
**Contact us**
|Before|After|
|---|---| …
=> LG-6453: Update page titles for Partners site

package.json
**Why**: So that we don't have to run the command multiple times
Thanks @aduth for the tip! https://github.com/18F/identity-site/commit/3986e0d565879663e8148976bb7b7b8d34ad612a#commitcomment-75115722
I will cherry-pick this on to `partners-redesign` branch if we do this
=> Add --multipass option

content/_partners/index._en.md
I confirmed that if the anchors are incorrect, `htmlproofer` will get cranky, so that will help us ensure these continue to work
=> Link to specific anchors on "our services" page (LG-6380)

_config.yml
I added the following override for preview branches, so this branch *should* still render:
```yaml
collections:
partners:
output: true
```
=> Disable HTML output for /partners site by default

content/_partners/security-experience._en.md
**Issue:** A few links are opening in a new window/tab, which isn't consistent with other link experiences.
**How:** Remove the target blank from these links on the `/security-experience/` page
> Is language around consent for sharing their data written in [plain language](https://www.plainlanguage.gov/) and [accessible](http://localhost:4000/accessibility/)?
🔗 [Federalist preview](https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.app.cloud.gov/preview/18f/identity-site/nng-remove-target-blank/partners/security-experience/)
Notes: There are three links to update on the `/contact/` form, but we don't have access to the embedded markup. Proposing this task to be bundled into another ticket ([Slack context](https://gsa-tts.slack.com/archives/C0184P9SCJ0/p1654537687035049))
=> LG-6500: Update links to open in the same window/tab

_config.yml
**Why**: Defaulting to rendering makes testing these new pages easier
I updated the configs already in federalist, this should be safe
=> Flip default rendering of partners site

_layouts/partners/faq.html
Why? Simple edits to the side nav on the faq page for partners.
=> changes to partners faq sidenav

_includes/partners/header.html, _sass/components/_nav.scss
**Issues on some mobile and tablet devices**
1. Lack of horizontal spacing between the logo and menu button
2. Lack of vertical spacing between `Login.gov | Developers.login.gov` links
👉🏼 [Federalist preview](https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.app.cloud.gov/preview/18f/identity-site/nng-lg-6557/partners/)
|---|---|
|![before-spacing](https://user-images.githubusercontent.com/6327082/172668722-35fade59-f301-4a7b-bf42-bfe869fc565b.png)|![after-spacing](https://user-images.githubusercontent.com/6327082/172668760-05eed28b-8300-4256-9f37-52283c1dd42c.png)|
=> LG-6557: /partners mobile logo and header issue

_config.yml, _includes/partners/impact-stories-navigation.html, _layouts/partners/rrb-impact-story.html, _layouts/partners/sba-impact-story.html, content/_partners_impact_stories/rrb._en.md, content/_partners_impact_stories/sba._en.md
- Creates a new collection, so that adding new impact stories is easier
There wasn't one JIRA for just this task, but it seemed to fall naturally out of LG-6534 and LG-6535
I know that @theabrad and @nickttng are also looking at some of the widths on impact stories, this was just a rough pass to add the sidenav, and not affect the rest. I chose to move the files to make new collections, so that may increase the chances of merge conflicts... apologies!
I think the nav here is too wide compared to [the Figma](https://www.figma.com/file/N4ivGLmr17PsrG1vEYcOxm/LG-5379-design-Iteration-partners.login.gov?node-id=1149%3A3957), but like I said, this is just the first pass
| --- | --- |
| <img width="1239" alt="Screen Shot 2022-06-08 at 3 48 01 PM" …
=> Add sidenav to partners impact stories (LG-6534, LG-6535)

_layouts/partners/impact-stories.html, _layouts/partners/our-services.html, _layouts/partners/rrb-impact-story.html, _layouts/partners/security-experience.html, _sass/components/partners/_partners.scss
**Issue:** There are instances when the content exceeds the line length of the optimal reading experience (~80 characters). 
**How:** This PR proposes various fixes until we have a better solution(s) in place, e.g., revamped layouts, the addition of side navigation, etc. Please feel free to propose a better way as well.
**Note:** This PR covers `/partners`-wide content brought up by these tickets.
- LG-6533
- LG-6534
- LG-6535
- LG-6556
Also, @theabrad, @zachmargolis, and I think that the PR should resolve all line length issues.
---
👉🏼 [Federalist preview](https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.app.cloud.gov/preview/18f/identity-site/nng-lg-6556/partners/)
| Example | Before | After |
|---|---|---|
| SBA Impact story | …
=> Partners site: Resolve width issues to improve reading experience

_includes/partners/impact-stories-navigation.html, _layouts/partners/impact-stories.html, content/_partners/impact-stories._en.md, content/_partners_impact_stories/rrb._en.md, content/_partners_impact_stories/sba._en.md
- Update URLs to be more directory-like /partners/impact-stories/:agency
- Sentence-case sidenav title
- Update landing page to use the same order as sidenav
- Fix URLs to work in preview pages
Lotta small changes, here are screenshots of the visible ones: (note, there are separate width changes in the visual diff not related to this specific PR)
| change | before | after |
| -- | --- | --- |
| landing page order: alphabetized | <img width="1166" alt="Screen Shot 2022-06-09 at 12 54 07 PM" src="https://user-images.githubusercontent.com/458784/172933196-f81e0301-97ca-4033-8cac-e58bc79bbcda.png">  |  <img width="1166" alt="Screen Shot 2022-06-09 at 12 53 59 PM" src="https://user-images.githubusercontent.com/458784/172933300-79e40e08-cb2a-46e2-aade-30812df19a67.png"> |
| sidenav: sentence …
=> Clean up partners impact stories pages

content/_partners/index._en.md
**Issue:** Several "U.S" alt texts are missing a "." (period) after "S" which increases the risk of mispronunciation with a screen reader. VoiceOver example: "U.Sarmy" instead of "U.S. (brief pause) Army."
The PR corrects them.
=> Correct alt text typos

_sass/components/_hero.scss
**Issue:** The `/partners` hero image is not displayed on a tablet.
**How:** Reconfigured media queries so that the partners hero image appears on a tablet. 
**Team Katherine** / @mdiarra3 / @jmdembe The PR addresses the Partners site but also touches the hero images of the brochure site; however, the impact should be minimal or none. Please feel free to review with this [preview link](https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.app.cloud.gov/preview/18f/identity-site/nng-lg-6579/).
👉🏼 [Federalist preview](https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.app.cloud.gov/preview/18f/identity-site/nng-lg-6579/partners/)
|---|---|
| ![federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5 app cloud gov_preview_18f_identity-site_partners-redesign_partners_](https:/ …
=> LG-6579: Fix missing partners hero image on a tablet

_includes/google_analytics.html
When writing code to capture a Google Analytics event, I came across this file initializing a Google Analytics instance that _wasn't_ the same as the destination for DAP analytics. There was nothing in the code indicating where this instance was or who it belonged to. It took me a while – and some help – to figure it out.
According to several slack posts, this isn't the first time this has happened. So the purpose of this PR is to add a comment indicating what instance we're hooking ourselves up to, so the next person that comes across this file doesn't have to go through the same process as those who came before.
=> Document destination of 2nd Google Analytics instance

spec/e2e/accessibility_spec.js
It was originally added as a workaround to the embedded contact form, but we migrated away from the embedded form to a natively-rendered form in #923.
=> Remove accessibility spec exception for partner contact page

_includes/partners/contact.html, spec/e2e/accessibility_spec.js, spec/e2e/support/target-blank.js
**Why**: Per our automated accessibility checks, we do not expect any links to open in a new tab. This is due to [accessibility recommendations](https://www.w3.org/TR/WCAG20-TECHS/G200.html). However, for certain scenarios like these (multi-step form), a new tab may be advisable to prevent loss of progress.
This resolves build failures currently occurring on the `main` branch. Unsure why this suddenly started failing (possibly a side-effect of #943), and why it did not fail in previous pull requests.
Related:
- #525
- https://www.w3.org/TR/WCAG20-TECHS/G200.html
=> Exclude form links from new tab accessibility testing

_config.yml, _layouts/contact_us.html
During phone number testing, the contact center noticed an increase in phone calls without a substantial decrease in the number of emails received. The centers hypothesis is that because the phone number is below the contact form, folks are submitting the contact form then calling (the center does not collect enough information on callers to confirm there are actually duplicates).
The contact center would like to run an experiment to move the phone number above the contact form to see if that has an impact on duplicates, and to see if it changes email vs phone call rates.
This PR adds a toggle (top, bottom) allowing us to easily change the location of the contact phone number on the page by overriding the value in Cloud.gov pages. Any value other than top or bottom results in the number …
=> Add toggle for contact phone number location on the webpage

_includes/header.html
This PR fixes the border bottom for the menu item on the brochure site to ensure uniformity
Before
After
=> Bugfix: add class to span in header

_data/en/settings.yml, _includes/partners/checklist.html, _includes/partners/footer.html, _includes/partners/header.html, _includes/partners/partners-banner.html, _layouts/partners/contact.html, _layouts/partners/faq.html, _layouts/partners/get-started.html, content/_partners/business-inquiries._en.md, content/_partners/contact._en.md, content/_partners/faq._en.md, content/_partners/state-and-local._en.md, content/_policy/contact._en.md, content/_policy/contact._es.md, content/_policy/contact._fr.md
Reverts #969, which introduced a bug that hid the "contact form" from help center pages behind a different name
| before revert | after revert |
| ---- | ---- |
| <img width="814" alt="Screen Shot 2022-10-24 at 5 03 35 PM" src="https://user-images.githubusercontent.com/458784/197652663-9d71b2f0-43df-4da7-ab76-1bc60d7cbab8.png"> | <img width="814" alt="Screen Shot 2022-10-24 at 5 03 38 PM" src="https://user-images.githubusercontent.com/458784/197652672-d6f3ff72-c81c-4453-810f-3f3093eeaf8a.png"> |
=> Revert Business Inquires PR

_data/en/settings.yml, _data/es/settings.yml, _data/fr/settings.yml, _includes/partners/checklist.html, _includes/partners/footer.html, _includes/partners/header.html, _includes/partners/partners-banner.html, _layouts/partners/contact.html, _layouts/partners/faq.html, _layouts/partners/get-started.html, content/_partners/business-inquiries._en.md, content/_partners/contact._en.md, content/_partners/faq._en.md, content/_partners/state-and-local._en.md, content/_policy/contact._en.md, content/_policy/contact._es.md, content/_policy/contact._fr.md
Reverts #973, which reverted #969, and adds a53e667aca61b2949aa25dfe7c0b0d4bbe36572f to resolve the original issue which had necessitated the revert.
Screen|Before|After
---|---|---
Main site footer|![Screen Shot 2022-10-25 at 8 23 34 AM](https://user-images.githubusercontent.com/1779930/197772456-f76231dd-76d9-4480-81d3-d437ffce8080.png)|![Screen Shot 2022-10-25 at 8 23 37 AM](https://user-images.githubusercontent.com/1779930/197772460-eb8538c7-8774-478a-b74c-911e80f9fd96.png)
Help center header|![Screen Shot 2022-10-25 at 8 23 44 AM](https://user-images.githubusercontent.com/1779930/197772463-fe8d142b-e69c-4e1e-95d3-9d9946b8406f.png)|![Screen Shot 2022-10-25 at 8 23 46 AM](https://user-images.githubusercontent.com/1779930/197772465-f9ebbe57-66b3-4bd0-9e06-79440fab464e.png)
Partner site …
=> Unrevert Business Inquiries text change

_data/en/settings.yml, _data/es/settings.yml, _data/fr/settings.yml, _includes/contact_phone.html
The contact center is going to expand their call-handling hours of operation starting 11/7 to 11am – 8pm eastern. This PR separates the hours of operation for calls and the contact form, and adds the new hours of operation for handling calls. 
This will be merged on 11/7 and – if everything goes according to today's plan – shown full time (so, no more taking the phone number off the page unless there is an exceptional circumstance).
=> Update contact center call-handling hours of operation

_layouts/partners/contact.html, _layouts/partners/faq.html, _layouts/partners/sba-impact-story.html, _sass/components/partners/_partners.scss
PR for [LG-7488](https://cm-jira.usa.gov/browse/LG-7488)
Header on impact stories page was not where it should be in the HTML. Also FAQ page sidebar was slightly misaligned as well so I removed a class there. Made the header take up the full width so sidebar and body always start underneath header. See screenshots below
=> Side nav incorrectly displayed on Impact stories page

content/_help/get-started/authentication-options._en.md, content/_help/get-started/authentication-options._es.md, content/_help/get-started/authentication-options._fr.md, content/_help/trouble-signing-in/how-to-sign-in._en.md, content/_help/trouble-signing-in/how-to-sign-in._es.md, content/_help/trouble-signing-in/how-to-sign-in._fr.md
**Why**: As a user consulting the help site, I want to make sure that the references for one-time codes is using the latest terminology so that I have a consistent experience between the application and help pages.
=> LG-6129: Change "security code" to "one-time code" for phone MFA

_config.yml, _plugins/style_guide_assets.rb, spec/output_spec.rb
Yes, we're an open source repo, but no, having the README accessible at https://login.gov/README.md is kind of sloppy.
Before:
- https://login.gov/README.md resolves (and others!! 😱 )
After:
- They do not!
=> Add lint to catch stray files exported to final site

.circleci/config.yml
Example failure: https://app.circleci.com/pipelines/github/18F/identity-site/3821/workflows/a6430e89-9072-486b-840e-b0f549274335/jobs/19124
Based on some hints that the `ffi` "cannot open shared object file" error could potentially be related to CircleCI cache:
- https://github.com/ffi/ffi/issues/881
- https://github.com/docker-library/ruby/issues/371
It doesn't _seem_ like it should be an issue, since the exact same cache state had previously passed in #1003.
If it doesn't work, we could explore some of the other options mentioned in comments on the above issue:
- https://github.com/ffi/ffi/issues/881#issuecomment-987996289
- https://github.com/ffi/ffi/issues/881#issuecomment-1189739345
=> Try busting CircleCI cache to resolve main build failures

_data/en/settings.yml, _data/es/settings.yml, _data/fr/settings.yml, _includes/contact_form.html
The contact center – both phone and contact-us-form support – has moved to 24/7 hours of operation. This PR updates site language to reflect that change. It also removes some language about support tickets taking up to 2 business days; the purpose of this change is to try and encourage folks to select that option (the contact center is aiming for a response in 6 hours or less).
=> Update contact hours to 24/7 for both phone and form, and remove extra support form copy

_data/en/settings.yml, _data/es/settings.yml, _data/fr/settings.yml, _includes/footer.html, _includes/partners/footer.html
Why: Since it's the canonical URL (avoid an unnecessary redirect)
Related Slack discussion: https://gsa-tts.slack.com/archives/C0NGESUN5/p1673266030524959
=> Update GSA links to use www subdomain

webpack.config.js
**Why?**
- It should have been included in #1019
- Improve build times
There's a non-negligible improvement on Webpack build times with these changes, about 17% faster (2370ms to 1968ms for an average of 5 runs).
=> Remove lingering IE11 supports

Gemfile, Gemfile.lock
Follow-up to #1003. In #1003, we opted for a Git reference to the yet-unpublished new version of `jekyll-sass-converter`. The new version has now been published to RubyGems, and we should prefer to use the gem version over cloning the Git reference (assumed to be more "stable", and faster install time).
=> Upgrade jekyll-sass-converter to published gem

.eslintignore, .gitignore, _config.yml, _includes/scripts.html, admin/config.yml, content/_help/manage-your-account/international-phone-support._en.md, content/_help/manage-your-account/international-phone-support._es.md, content/_help/manage-your-account/international-phone-support._fr.md, content/_partners/business-inquiries._en.md, content/_policy/contact._en.md, content/_policy/contact._es.md, content/_policy/contact._fr.md, spec/output_spec.rb, webpack.config.js
This pull request changes the JavaScript to directly output files into the built `_site` directory.
Currently, JavaScript files are built to the `assets` source directory, which has several downsides:
- It's prone to race conditions which can occur between when JavaScript and Jekyll builds start and finish
- It relies on Jekyll to copy JavaScript assets, which is both slow, and triggers Jekyll rebuilds on JavaScript file changes despite the fact that Jekyll is not responsible for transforming these files
- It requires additional workarounds to differentiate and ignore JavaScript artifacts, as opposed to treating `_site` as the primary artifact of the build
This change also follows from previous efforts which apply a similar approach to Sass (#1000 changes to compile Sass directly to …
=> Build JavaScript files to site output directory

_layouts/contact_us.html, content/_policy/contact._en.md, content/_policy/contact._es.md, content/_policy/contact._fr.md
This reverts commit 3b21b3d617a0f9868ad001a3f73f3a704365a57a from #1032
The banner has been disabled via config in the pages admin, so this puts back the old message and old layout
=> Revert "Add outage message for Salesforce outage"

_includes/components/footer-navigation.html, _sass/components/_footer.scss
**Why**: Try to limit to single `h1` per page, avoid treating footer navigation headings as equal hierarchy to page heading.
Related:
- https://www.a11yproject.com/posts/how-to-accessible-heading-structure/
- https://gsa-tts.slack.com/archives/C02BT4H5Q/p1676588237094159
=> Use h2 for footer navigation section headings

_includes/partners/contact.html
Not a specific ticket, issue was shared in [slack](https://gsa-tts.slack.com/archives/C01SU3NB9T3/p1677075290006339)
Fixed typo of `you rapplication(s)` to `your application(s)`.
=> Fix typo on contact form

content/_help/verify-your-identity/verify-your-identity-in-person._en.md, content/_help/verify-your-identity/verify-your-identity-in-person._es.md, content/_help/verify-your-identity/verify-your-identity-in-person._fr.md
[LG-8824](https://cm-jira.usa.gov/browse/LG-8824)
Add "American Samoa" to /help/verify-your-identity/verify-your-identity-in-person.  It should be added to section "Your state-issued ID" after US Virgin Islands.
Visit each view below. Find section Your state-issued ID. Confirm American Samoa has been added. Translation for each language can be found in the ticket. 
📝 make lint returns 79 valid files
📝 npm test for `gyamada/lg-8824-add-american-samoa-v2` & `main` return the same results: 1 failed, 383 passed with the failure observed in this file `contact_us_form_element_spect.ts`
=> LG-8824:  Add "American Samoa" to verify-your-identity-in-person help content

_data/es/settings.yml, content/_policy/accessibility._en.md, content/_policy/accessibility._es.md, content/_policy/accessibility._fr.md
**Why?**
* These pages were removed from the design system documentation site between https://github.com/18F/identity-style-guide/pull/178 and https://github.com/18F/identity-style-guide/pull/181
* We are working to remove references to the design system documentation site
=> Remove reference to design system accessibility link

package-lock.json, package.json
**Why:**
- Resolve security advisory
- Take advantage of latest features, bug fixes, and performance enhancements
- Reduce future maintenance burden caused by version drift
Replaces #1053, in order to update to the actual latest version (5.76.1, not 5.76.0), so that CI can run, and to include upgrade to `webpack-cli` in addition to `webpack` dependency.
Refer to release notes for major version `webpack-cli@5.0.0` changes (mostly related to dropping support for Webpack 4): https://github.com/webpack/webpack-cli/releases/tag/webpack-cli%405.0.0
=> Bump Webpack to latest version (5.76.1)

_plugins/sort_by_values.rb
**Why:** As a user submitting a support ticket, I expect that I can scan for the name of the relevant agency in an ordered list, so that I can quickly find and select it from the long list of options.
**Testing Instructions:**
1. Go to https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/18f/identity-site/aduth-lg-9179-contact-form-agency-sort/contact/
2. Expand "Partner Agency" dropdown
3. Find "myTreasury" partner agency option
_Before:_ You'd find it at the very end of the list (see [live page](https://login.gov/contact/))
_After:_ You'll find it alphabetically between "Library of Congress" and "National Aeronautics and Space Administration"
=> LG-9179: Sort Contact Us agencies case-insensitive

_includes/contact_form.html
[LG-9179](https://cm-jira.usa.gov/browse/LG-9179)
Updates the list of Common Applications in the Partner Agency dropdown of the Contact Us page to be listed alphabetically, in order to reduce cognitive load in trying to navigate the list of common applications.
Related: #1058
See Slack discussion: https://gsa-tts.slack.com/archives/C01710KMYUB/p1679494482124409?thread_ts=1679489133.583309&cid=C01710KMYUB
1. Go to https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/18f/identity-site/aduth-lg-9179-contact-common-alphabetical/contact/
2. (Optional) Change the page language
3. Expand "Partner Agency" dropdown
4. Observe that the list of Common Applications is sorted alphabetically
If relevant, include a …
=> LG-9179: Sort "Contact Us" common agencies alphabetically

_config.yml, _includes/contact_form.html, assets/js/contact.js, package-lock.json, package.json, spec/output_spec.rb
Based on request [in Slack](https://gsa-tts.slack.com/archives/C0NGESUN5/p1679931537439049)
Adds a site config where we can add SHA 256 of individual email addresses that misbehave, so we can prevent submissions from them that spam the contact center
=> Add config to block email addresses that spam the contact center

assets/js/country_support.js, package-lock.json, package.json
Removes the [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) polyfill and related logic.
Why?
- It's available in all supported browsers ([source](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API#browser_compatibility))
- Reduces maintenance overhead and vulnerability surface area of dependencies
- Simplifies code
- Reduces bundled JavaScript size
View preview at: https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/18f/identity-site/aduth-rm-fetch-polyfill/help/manage-your-account/international-phone-support/
```
make build
npm exec jest spec/e2e/country_support_spec.js
```
=> Remove fetch polyfill

content/_help/verify-your-identity/troubleshoot-uploading-your-state-issued-id._en.md, content/_help/verify-your-identity/troubleshoot-uploading-your-state-issued-id._es.md, content/_help/verify-your-identity/troubleshoot-uploading-your-state-issued-id._fr.md
[LG-9311](https://cm-jira.usa.gov/browse/LG-9311)
Update `/help/verify-your-identity/troubleshoot-uploading-your-state-issued-id/` in all three languages to state that a user will be rate-limited after 5 attempts to upload their drivers license.
<details>
<summary>Before:</summary>
</details>
<details>
<summary>After:</summary>
</details>
=> LG-9311 Correct number of upload attempts from 10 to 5 for all three languages

_includes/components/2-col.html, _includes/components/3-col.html, _includes/components/create-an-account.html, _includes/partners/checklist.html, _includes/partners/x-col.html, _layouts/help.html, _layouts/sidenav.html, _sass/components/_typography.scss, content/_landing/help._en.md, content/_landing/help._es.md, content/_landing/help._fr.md
[LG-9385: 508 - The structure of information cannot be understood by assistive technology
](https://cm-jira.usa.gov/browse/LG-9385)
**Explanation**
This ticket/PR was born out of an audit conducted by the VA. One of the findings they reported was "On the Create an account | Login.gov screen (Create an account), under Create an account, the information starting with When you’re ready to create your secure … is read as an article." This 
means that when a user uses a web rotor to navigate a website through landmarks, the part of the website containing content is in an `article` landmark. This happens because that part of the page is coded as an `<article>` which means that the element is announced as `article`
**Fix**
Change instances of `<article>` to a `<div>`. With this change, we get …
=> [LG-9385] 508 - The structure of information cannot be understood by assistive technology

_includes/header--help.html, _includes/header.html, _includes/hero--search.html, _includes/partners/header.html, _layouts/landing.html, _layouts/sidenav.html, _sass/components/_hero.scss, _sass/components/_layout.scss, _sass/components/_nav.scss, _sass/pages/_partners.scss, package-lock.json, package.json
Updates Login.gov Design System from v7.0.0 to v7.0.1, which fixes default navigation styling.
The changes here are significant only because the brochure site previously implemented most of its navigation behaviors as custom. The revisions reflect a return to stock design system styling.
There may be subtle visual differences, though it is expected to largely look and feel the same as the live site.
Follows #1071
Note: The `@18f/identity-design-system` dependency will be updated to point to the stable release of 7.0.1 before merging.
Preview link: https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/18f/identity-site/aduth-lgds-7-0-1/
Concentrate focus on:
1. Different viewport sizes
2. Different layouts
1. [Main site …
=> Upgrade Login.gov Design System to v7.0.1

_layouts/sidenav.html, spec/e2e/accessibility_spec.js
[LG-9389](https://cm-jira.usa.gov/browse/LG-9389)
Updates the "Back to top" link to reset focus to the beginning of the page's main content area, so that someone navigating content with keyboard or assistive technology can proceed as expected from the top of content.
The "Back to top" link now links to the same anchor target as the "Skip to main content" skip link at the beginning of the page.
**Technical Notes:**
The previous `href="#top"` is a valid anchor reference, but its behaviors defined in the specification seem to specifically exclude any change in focus, vs. if there's a target element associated with the `href`:
>if document's indicated part is top of the document, then: [...] Scroll to the beginning of the document for document.
>
>[...]
>
>Otherwise: [...] Let target be …
=> LG-9389: Reset focus to top of content for "Back to top" links

_sass/components/_search.scss, _sass/components/all.scss
[LG-9624](https://cm-jira.usa.gov/browse/LG-9624)
Styles the search field to hide the "X" clear button that shows in Chrome when text is entered in the field, so that the field provides a consistent experience regardless of input type (mouse vs. keyboard). There should not be any interactive elements which can only be activated with a mouse.
Related:
- https://github.com/uswds/uswds/issues/5277
- https://bugs.chromium.org/p/chromium/issues/detail?id=1147314
1. In Chrome, go to https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/18f/identity-site/aduth-lg-9624-search-clear-button/
2. Enter text in the search field
3. Observe there is no button to clear the search contents
Before|After
---|---
=> LG-9624: Hide search clear button

_data/en/settings.yml, _data/es/settings.yml, _data/fr/settings.yml
Change the navigation label to "Primary Links and Secondary Links" to prevent the screen reader from reading "navigations" twice.
=> LG-9626: add clearer primary navigation name

_includes/country_support_table.html, _sass/components/_sticky-table.scss
Fixes the appearance of headers on the international phone support help center page.
Why?
- Expected to show with a white background, but wasn't appearing as expected due to CSS specificity conflict
- Add border for visual distinction
1. Go to https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/18f/identity-site/aduth-fix-sticky-header-bg/help/manage-your-account/international-phone-support/
3. ~Scroll page and observe table header appearance~ Cry because our preview environments aren't set up to load the data 😢 
Before|After
---|---
=> Fix appearance of phone support sticky headers

_config.yml, _layouts/contact_us.html, content/_policy/contact._en.md, content/_policy/contact._es.md, content/_policy/contact._fr.md
[LG-9967](https://cm-jira.usa.gov/browse/LG-9967)
Adds a new option to configure whether to mention the availability of the contact center phone number during a scheduled maintenance window.
**Why?** The default maintenance window content does not mention the contact center phone number, but it will be available during the upcoming planned maintenance window on June 10th.
Test the following combinations of outages to ensure content appears as expected, by adding these to a local `_config.dev.yml` file:
**Planned outage, phone available:**
```yml
contact_maintenance_start_time: '2023-05-10T16:00:00Z'
contact_maintenance_end_time: '2023-06-10T16:05:00Z'
```
([See expected screenshot](https://github.com/18F/identity-site/assets/1779930/eb462220-177c-486f-9ebf-f021776290d5))
**Planned outage, …
=> LG-9967: Support option for phone available in planned maintenance

README.md, docs/development-workflows/branching-and-publishing-workflow.md, docs/development-workflows/contact-form-outages.md, docs/development-workflows/nested-help-articles.md, docs/development-workflows/netlify-cms.md
Splits the `README.md` file into separate "Guides for Common Workflows" Markdown files, linked at the top of the README. This should better support scalability and help someone find the information they need, since the current README currently contains quite a bit of information, not all of which is always relevant depending on the audience.
It also adds a new guide for handling outages, which is a common workflow, and one which is usually time-sensitive in the case of an unplanned outage.
(Base is temporarily set to #1095, and will update to `main` after #1095 is merged)
=> Restructure README to split guides to docs directory, add "Outages" documentation

content/_policy/rules-of-use._en.md, content/_policy/rules-of-use._es.md, content/_policy/rules-of-use._fr.md
Replaces a link which currently 404s with an up-to-date reference, using a direct link to the relevant US Code, following the pattern from the US code reference immediately preceding it in the same sentence.
This will fix an ongoing build failure present on all branches.
Old link (404): https://www.gsa.gov/cdnstatic/CNXII__Eligibility_to_Use_GSA.pdf
New link: https://uscode.house.gov/view.xhtml?req=granuleid:USC-prelim-title40-section501&num=0&edition=prelim
Related Slack thread: https://gsa-tts.slack.com/archives/C0NGESUN5/p1686312424292629
1. Go to https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/18f/identity-site/aduth-replace-404-link/policy/rules-of-use/
2. Click "40 USC § 501", under "6. Authorities"
3. Observe that you see content related to 40 …
=> Replace broken link for US Code authority

content/_help/specific-agencies/sam._en.md, content/_help/specific-agencies/sam._es.md, content/_help/specific-agencies/sam._fr.md
Updates SAM.gov links to direct users to the root path homepage.
Why?
- It's where the user arrives by this link anyways
- May be remnant of the older site (redesigned in 2022)
- Hopefully resolves some intermittent build failures for the daily external link checker
- Changing from www.sam.gov to [sam.gov](https://sam.gov) skips a redirect hop, so the user arrives where they want without delay
- `$ curl -I --silent https://www.sam.gov | grep Location:`
- `Location: https://sam.gov/`
Related Slack discussion: https://gsa-tts.slack.com/archives/C0NGESUN5/p1686398830922189
1. Go to https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/18f/identity-site/aduth-sam-gov-homepage/help/specific-agencies/sam/
2. Click either of the "SAM.gov" links
3. Observe that you …
=> Change SAM.gov link to bare path homepage

README.md, docs/development-workflows/configuring-site-settings.md, docs/development-workflows/contact-form-outages.md
Builds on #1098 to add a new guide for how to edit any site settings. There were fragmented references previously to local development settings and outage handling, but this wasn't broadly applicable, and missed a few steps (e.g. requesting access, rebuilding branches after saving changes).
Related Slack discussion (private channel): https://gsa-tts.slack.com/archives/C046YTLTK6U/p1686334353060939
1. Follow the guide and see if you can understand where to add settings
=> Add workflow guide for managing site settings

.svglintrc.js, Makefile, package-lock.json, package.json
Removes the SVG `viewBox` linter script.
**Why?**
- This linter was added to prevent regressions where the absence of a `viewBox` attribute would create issues with SVG images shown in Internet Explorer, but we no longer support Internet Explorer.
- Reduce size of dependency tree, improving installation time and reducing maintenance burden and vulnerability surface area associated with additional dependencies (e.g. see #1105).
Alternative to #1105
1. Build passes
=> Remove viewbox linter

.circleci/config.yml, Makefile, _data/en/settings.yml, _data/es/settings.yml, _data/fr/settings.yml, _data/nav.yml, package-lock.json, package.json
Adds an enforces YAML normalization, using the `@18f/identity-normalize-yaml` package published from `identity-idp` in https://github.com/18F/identity-idp/pull/8654.
**Why?**
- Improved typography using punctuation formatters
- Also resolves some existing inconsistency where we previously used smart quotes in some places, either due to Jekyll's built-in smart quotes handling or where content was copied from some other source
- Consistency of content formatting in YAML files
- Improved readability by enforced key alphabetization
```
make lint_yaml
```
Ensure no regressions in displayed content in [preview site](https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/18f/identity-site/aduth-normalize-yaml/).
=> Add YAML normalization

content/_help/trouble-signing-in/forgot-your-personal-key._en.md, content/_help/trouble-signing-in/forgot-your-personal-key._es.md, content/_help/trouble-signing-in/forgot-your-personal-key._fr.md, content/_help/trouble-signing-in/issues-with-authentication-methods._en.md, content/_help/trouble-signing-in/issues-with-authentication-methods._es.md, content/_help/trouble-signing-in/issues-with-authentication-methods._fr.md
[LG-10168](https://cm-jira.usa.gov/browse/LG-10168), an implementation of [LG-9890](https://cm-jira.usa.gov/browse/LG-9890)
Per [LG-9890](https://cm-jira.usa.gov/browse/LG-9890), Team Katherine developed a troubleshooting article to support face/touch unlock, "Issues with authentication methods," which also covers common non-FT MFA troubleshooting problems identified by Dylan Bowling and Rachel Houghton from the support team.
This article has been created in markdown for EN, ES and FR and assigned an order of 3 in the taxonomy. The previous order 3 article, "Forgot your personal key," has been moved to order 4.
Since this article contains information valuable even for people who are already using face/touch unlock from the previous launch, this can be merged even prior to the phase 1 …
=> Create new "Issues with Authentication Methods" page with translations

docs/development-workflows/netlify-cms.md, package-lock.json, package.json, spec/output_spec.rb, webpack.config.js
[LG-9268](https://cm-jira.usa.gov/browse/LG-9268?filter=-1)
* Imports react and react-dom
* Imports the `@18f/identity-address-search` library
* Configures webpack to properly bundle PO search React modules
Note: this PR doesn't begin using the new address search components, it just configures them for later use. You can see a demo of these components on [this branch](https://github.com/18F/identity-site/pull/new/sbachstein/lg-9268-address-search-prototype). It's on the `/contact` page.
To try a demo of the address search components you can:
- there are no i18n strings setup, a future ticket will configure i18n
- there is no functional API for the components to interact with, future tickets will setup an API
**Note: this is a screenshot of the prototype branch …
=> LG-9268: Import PO search library

_includes/alert.html, _includes/contact_form.html, _includes/country_support_table.html, _layouts/contact_us.html, assets/js/contact.js, content/_help/trouble-signing-in/issues-with-authentication-methods._en.md, content/_help/trouble-signing-in/issues-with-authentication-methods._es.md, content/_help/trouble-signing-in/issues-with-authentication-methods._fr.md
Follow-up to: https://github.com/18F/identity-site/pull/1123#discussion_r1261691663
Refactors existing ad-hoc alert HTML to use the `alert.html` partial added in #1123.
This was slightly more complicated than initial expected, due to the various customizations we apply to alerts through attributes.
Verify no regressions in affected pages, including in Spanish and French locales:
- http://localhost:4000/contact/
- Outage banner
- Refer to https://github.com/18F/identity-site/blob/main/docs/development-workflows/contact-form-outages.md
- PII banner (when submitting with 4 digits in comment field)
- http://localhost:4000/help/trouble-signing-in/issues-with-authentication-methods/
- Note: Two alerts in this page
- http://localhost:4001/help/manage-your-account/international-phone-support/
- …
=> Consistently use alert "component" partial

_data/en/settings.yml, _data/es/settings.yml, _data/fr/settings.yml, _includes/contact_form.html
[LG-10067](https://cm-jira.usa.gov/browse/LG-10067)
Removes from the topicMap array the Other Topic.
Other as a Topic has no subtopic Issue. 
Issue is a required field so when a user selects Other they cannot select an Issue and so cannot submit the form.
Relabel 'Feedback for Login.gov' to 'Feedback or other'
=> Bug Fix Contact Us form - Remove 'Other' Topic

_data/en/settings.yml, _data/es/settings.yml, _data/fr/settings.yml
[LG-10404](https://cm-jira.usa.gov/browse/LG-10404)
This PR adds the State of Arkansas to the contact form on the brochure site
In the sandbox environment, 
For testing: Create a sample help ticket with "State of Arkansas" as the partner agency.
=> Add state of Arkansas to Contact Us form

content/_landing/create_an_account._en.md, content/_landing/create_an_account._es.md, content/_landing/create_an_account._fr.md, content/_landing/what_is_login._en.md, content/_landing/what_is_login._es.md, content/_landing/what_is_login._fr.md, content/_landing/who_uses_login._en.md, content/_landing/who_uses_login._es.md, content/_landing/who_uses_login._fr.md, spec/all_pages_spec.rb
Updates and adds enforcement that we don't internally link to "old" URLs.
**Why?**
- So that our links always direct to the most up-to-date content
- To avoid an extra redirect hop for users who follow these links
Ensure that the affected content still links to the expected page.
=> Avoid internal linking to legacy URLs

_includes/header--help.html, _includes/help/nav_sidenav.html, _includes/hero--search.html, _includes/partners/header.html, _includes/search.html, _layouts/help_landing.html
[LG-10350](https://cm-jira.usa.gov/browse/LG-10350)
Updates searches performed in Help Center and Partners site to filter automatically to results for "Login.gov account help" and "For partners" Search.gov collections respectively.
Reference:
- https://search.gov/admin-center/activate/code.html#option-1-limit-to-collections
- https://search.usa.gov/sites/8022/collections
1. Go to http://localhost:4000
2. Search for something
3. Navigate to a different page
4. Try mobile searching too
Expect that search results are filtered based on where you search from:
- Help landing page or article? Filters to "Login.gov account help"
- Partner site? Filters to "For partners"
- Neither of the above? Shows "Everything" results
=> LG-10350: Filter search collection for Help & Partners

content/_help/verify-your-identity/how-to-verify-your-identity._en.md, content/_help/verify-your-identity/how-to-verify-your-identity._es.md, content/_help/verify-your-identity/how-to-verify-your-identity._fr.md
[LG-10491](https://cm-jira.usa.gov/browse/LG-10491)
The sentences "If you are under 18 years of age, you may not be able to verify your identity for a Login.gov account. If you have trouble verifying your identity, please contact the partner agency to find out what you can do." replaces "You will need to verify your identity and secure your account." in the English, Spanish, and French versions of 5.4.1 How to Verify your identity.
| English | Spanish | French |
| ----------- | ----------- | ------------- |
| ![Screenshot 2023-08-11 at 11 41 45 AM](https://github.com/18F/identity-site/assets/2381438/503828ba-5c51-412b-9a7e-08f45a0195b2) | ![Screenshot 2023-08-11 at 11 42 14 AM](https://github.com/18F/identity-site/assets/2381438/de112c44-f078-4241-8b84-99caf6eb641c) | ![Screenshot …
=> LG-10491 Update how-to-verify-your-identity with info for people under 18 years old

package-lock.json, package.json
https://cm-jira.usa.gov/browse/LG-10861
This PR bumps the version of the identity-design-system to 7.1.0. As of 08/28/2023 that release doesn't exist yet. [This PR](https://github.com/18F/identity-design-system/pull/371) captures the work to create the release.
- It's pretty unlikely that there's anything broken, but it's definitely worth looking through the preview.
=> LG-10861: Use New Version of identity-design-system

docs/development-workflows/contact-form-outages.md
Updates the "Contact Form Outage" workflow guide to cover a scenario where only the phone line is experiencing an outage, but the online support form is still available.
**Why?**: In case of an outage affecting only the phone line where a user can still use the online support form, we can configure that only the phone number be removed from the page.
Preview: https://github.com/18F/identity-site/blob/aduth-outage-runbook-phone-only-outage/docs/development-workflows/contact-form-outages.md
Related:
- Example incident: https://status.login.gov/incidents/kypwq01dq7gs
- Slack discussion: https://gsa-tts.slack.com/archives/C20J64X6V/p1693396986141389
Try following the runbook and applying configuration in local environment, and verify the expected result.
=> Update outage runbook to cover phone-only outage

assets/js/post_office_search.tsx, package-lock.json, package.json, tsconfig.json, webpack.config.js
Updates Post Office Search script to use TSX, including required changes to Webpack and TypeScript configurations.
**Why?**
- All of our new scripts should be written in TypeScript
- So that we have the capability of using JSX/TSX file extensions
- So a developer knows to expect JSX syntax
Continues: https://github.com/18F/identity-site/pull/1156#discussion_r1312226619
```
npm run build:js && npm run typecheck
```
=> Rename post_office_search to TSX

scripts/TOUCHPOINTS.md, scripts/_touchpoints.yml, scripts/touchpoints.rb
This transient script is meant to alleviate issues with the Touchpoint dashboard, which is having difficulty displaying results for Login.gov IDP survey results.
[LG-10566](https://cm-jira.usa.gov/browse/LG-10566)
=> Create a script to download Touchpoint API results

_sass/components/_icon-list.scss, _sass/components/_image-example.scss, _sass/components/all.scss
This is a followup to the various help center work in [this epic](https://cm-jira.usa.gov/browse/LG-10667). Most specifically it's a followup to [this ticket](https://cm-jira.usa.gov/browse/LG-10527) and this [thread](https://gsa-tts.slack.com/archives/C056RD1NEHW/p1694548172264059?thread_ts=1694465060.661489&cid=C056RD1NEHW).
This PR changes the margin on two pages so the spacing looks correct. There's a followup ticket ([LG-11013](https://cm-jira.usa.gov/browse/LG-11013)) for cleaning up these styles in the design system.
=> Add Custom Style to Fix Margin

scripts/htmlproofer
Updates HTMLProofer script to include `Accept-Language` header in requests, to resolve issues with some URLs.
See: https://gsa-tts.slack.com/archives/C0NGESUN5/p1697458092491079
Build should pass.
=> Add Accept-Language header to HTMLProofer requests

content/_help/verify-your-identity/verify-your-identity-in-person/find-a-participating-post-office._en.md, content/_help/verify-your-identity/verify-your-identity-in-person/find-a-participating-post-office._es.md, content/_help/verify-your-identity/verify-your-identity-in-person/find-a-participating-post-office._fr.md, spec/e2e/post_office_search_spec.ts
[LG-11267](https://cm-jira.usa.gov/browse/LG-11267) Enable PO Search in the Help Center (While working on this ticket- I discovered we did not have translations for the title and we did not have a meta- title- aka side navigation). This view and the side navigation is currently turned off in production. I wanted to make this separate PR to handle these translations for preparation of enabling the flag that way that code is separate and isolated. 
[Gengo]( https://gengo.com/c/job/details/91967897/)
[French](https://docs.google.com/document/d/13qxL_ws3Gdi-bg37YNQ1nRCgjnvBpl-H/edit?usp=drive_link&ouid=116141035080166034135&rtpof=true&sd=true)
[Spanish](https://docs.google.com/document/d/1zNEllAMmm-jvfA5f6Mazye7ihZMrsqOu/edit?usp=drive_link&ouid=116141035080166034135&rtpof=true&sd=true)
1. …
=> Add translations for title and add sidenav title for PO Search

spec/all_pages_spec.rb
Unskips the test which asserts that all in-page links reference a valid heading by ID.
I noticed this as being skipped but it appears to pass as-is, and would be a useful test to enforce.
```
bundle exec jekyll build
rspec spec/all_pages_spec.rb
```
=> Unskip valid headers test

README.md, _includes/components/post-office-search.html, _sass/_index.scss, _sass/pages/_find_a_participating_post_office.scss
[LG-11861 ](https://cm-jira.usa.gov/browse/LG-11861) Implementation: Fix spacing in the PO Search results
- Add documentation on how to get mock data for PO Search buildings locally
- Create css stylesheet for Find a Participating Post Office
- Alpha order and add new style sheet into index.scss file
**Locally**
**Review App**
=> LG-11861 Fix Spacing In PO Search Results

.github/pull_request_template.md
This PR has a pre-populated link for tickets like we do in the `identity-idp` repo.
=> update pr template with ticket link pre-populated

content/_partners/faq._en.md
[LG-11977](https://cm-jira.usa.gov/browse/LG-11977)
Add American Samoa on the login.gov partners site for accepted forms of Id.
If relevant, include a screenshot or screen capture of the changes.
|<img width="824" alt="Screenshot 2024-01-24 at 11 35 51 AM" src="https://github.com/18F/identity-site/assets/1034049/c17bdf2f-48d3-4603-bf64-de4bed4dc819"> |  <img width="846" alt="Screenshot 2024-01-24 at 11 31 22 AM" src="https://github.com/18F/identity-site/assets/1034049/3b50751d-baf3-4798-8cc8-22c3d3761e61">|
=> LG-11977: Add American Samoa to updated forms of ID partners site

_includes/footer.html, _includes/partners/footer.html
Replaces the footer link for "No Fear Act", which currently 404's, with its equivalent replacement.
See Slack discussion: https://gsa-tts.slack.com/archives/C0NGESUN5/p1707134895579009
1. Go to https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/18f/identity-site/aduth-no-fear-act-url/
2. Click "No Fear Act data" in the footer
3. Observe that you're taken to a resource for "Notification and Federal Employee Antidiscrimination and Retaliation Act of 2002: Equal Employment Opportunity No FEAR Act Posting"
=> Replace broken link to No Fear Act footer resource

spec/e2e/accessibility_spec.js, spec/e2e/support/puppeteer-environment.js
Updates existing accessibility tests to run each page's analysis concurrently, using [Jest's `test.concurrent.each`](https://jestjs.io/docs/api#testconcurrenteachtablename-fn-timeout).
The goal of these changes is to reduce the time to complete the continuous integration build, which currently takes upwards of 10 minutes to complete, with most time spent at this step.
The impact is about **35% reduction in the e2e job time**, from around [6m45s](https://app.circleci.com/pipelines/github/18F/identity-site/5431/workflows/af243003-adf9-4a08-89ff-f20ceab10764?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) to [4m15s](https://app.circleci.com/pipelines/github/18F/identity-site/5430/workflows/943a9267-3c21-4aff-bd73-2bb7529a57d4).
The …
=> Run accessibility page tests concurrently

.circleci/config.yml
Updates `install-dependencies` CircleCI command to improve the effectiveness and performance of dependency installation.
Specifically, it changes from caching the project's local `node_modules` directory to the `~/.npm` directory, which is the default global cache directory. It also combines the Bundler and NPM caches.
In practice, this results in a smaller cache size (faster to restore and save) and less time at the NPM installation step.
And since the `install-dependencies` command happens multiple times throughout workflows, the savings are multiplicative.
[**Before**](https://app.circleci.com/pipelines/github/18F/identity-site/5431/workflows/af243003-adf9-4a08-89ff-f20ceab10764/jobs/29918): 1s (Restore bundler cache) + 14s (Restore npm cache) + 26s (Install dependencies) = 41 seconds …
=> Use home npm cache directory for CircleCI dependencies cache

content/_help/verify-your-identity/accepted-identification-documents._en.md
[LG-12089](https://cm-jira.usa.gov/browse/LG-12089)
Updated help center copy about what forms of ID we accept to conform to login.gov style guide.
Specifically:
- Changed "US" to "U.S."
- Added Oxford commas
|![image](https://github.com/18F/identity-site/assets/101212334/8de9a8ef-b867-4ba6-92b3-589f24a6f0d7)| ![image](https://github.com/18F/identity-site/assets/101212334/130580f5-2758-4a97-a5d2-e88bac731afd) |
=> Added periods to "US" and made conform to Oxford comma usage.

_includes/components/icon-list.html, _includes/components/icon.html, _includes/language_picker.html, _sass/components/_language-picker.scss
Refactors the language picker to use [the design system icon component](https://designsystem.digital.gov/components/icon/) instead of ad hoc images.
This is an incremental step toward upgrading to [the latest version of the design system](https://github.com/18F/identity-design-system/releases/tag/v9.0.0), which removes the images `angle-arrow-down.svg` and `angle-arrow-up.svg` which are updated here.
This also aligns to the IdP implementation introduced in https://github.com/18F/identity-idp/pull/10098, including improvements there to add an animation to the toggle, as well as avoiding flickering appearance of an image when first toggling the dropdown.
Verify that there are no regressions in the appearance or function of the language picker. Note that there are different language picker …
=> Refactor language picker using icon component

content/_help/verify-your-identity/accepted-identification-documents._en.md, content/_help/verify-your-identity/accepted-identification-documents._es.md, content/_help/verify-your-identity/accepted-identification-documents._fr.md, content/_help/verify-your-identity/how-to-add-images-of-your-state-issued-id._en.md, content/_help/verify-your-identity/how-to-add-images-of-your-state-issued-id._es.md, content/_help/verify-your-identity/how-to-add-images-of-your-state-issued-id._fr.md
Replaces instances of "green" and "red" design system color tokens with equivalent "success" and "error" tokens.
This is an incremental step toward upgrading to [the latest version of the design system](https://github.com/18F/identity-design-system/releases/tag/v9.0.0), which removes raw color tokens. As noted in the CHANGELOG, these colors are also incorrect.
1. Visit affected pages to verify that the icon list icons appear in the expected green and red colors:
1. https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/aduth-stateful-colors/help/verify-your-identity/accepted-identification-documents/
2. https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/aduth-stateful-colors/help/v …
=> Replace raw color tokens with stateful alternatives

_includes/language_picker.html, _sass/components/_accordion.scss, _sass/components/all.scss
This enhances accordion styles to appear hidden while JavaScript is loaded if expected to be collapsed once JavaScript finishes loading.
The benefit is that this avoids the appearance of flashing content. This is especially noticeable with the language picker element, which is implemented as an accordion and is displayed at the top of the page.
See upstream pull request: https://github.com/uswds/uswds/pull/5826
1. Go to https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/aduth-accordion-js-loading/
2. Refresh the page with cache disabled (either hard refresh with <kbd>Shift</kbd><kbd>⌘</kbd><kbd>R</kbd> in Chrome, or "Disable cache" in the Network tab of developer tools)
3. Observe that the language picker always appears collapsed …
=> Hide accordion content while JavaScript loads

_data/en/settings.yml, _data/es/settings.yml, _data/fr/settings.yml, spec/data_spec.rb
Removes unused values from `settings.yml` files within `_data`, and adds a test case to ensure that keys are consistent between all languages.
Related comment: https://github.com/GSA-TTS/identity-site/pull/1226#discussion_r1541338931
Identifying lack of use required some manual effort, specifically searching `settings.[key]`
```
bundle exec rspec spec/data_spec.rb
```
Verify no lingering references in code to removed keys.
=> Remove unused data keys

content/_help/verify-your-identity/verify-your-identity-in-person._en.md, content/_help/verify-your-identity/verify-your-identity-in-person._es.md, content/_help/verify-your-identity/verify-your-identity-in-person._fr.md
[LG-12805](https://cm-jira.usa.gov/browse/LG-12805)
=> LG-12805 verify your id in person

_config.yml, _includes/help/nav_sidenav.html, _includes/help/translate_page.html, content/_help/trouble-signing-in/face-or-touch-unlock._en.md, content/_help/trouble-signing-in/forgot-your-personal-key._es.md, content/_help/trouble-signing-in/forgot-your-personal-key._fr.md, content/_help/trouble-signing-in/how-to-sign-in._en.md, content/_help/verify-your-identity/how-to-add-images-of-your-state-issued-id._en.md, content/_help/verify-your-identity/how-to-add-images-of-your-state-issued-id._es.md, content/_help/verify-your-identity/how-to-add-images-of-your-state-issued-id._fr.md, content/_help/verify-your-identity/how-to-verify-your-identity._en.md, content/_help/verify-your-identity/how-to-verify-your-identity._es.md, content/_help/verify-your-identity/how-to-verify-your-identity._fr.md, content/_help/verify-your-identity/verify-your-identity-in-person._en.md, content/_help/verify-your-identity/verify-your-identity-in-person._es.md, content/_help/verify-your-identity/verify-your-identity-in-person._fr.md, spec/all_pages_spec.rb
This adds a test so that we do not internally link to pages that have been moved.
=> add redirect_from test

_sass/components/_sticky-table.scss
Noticed a small visual bug on the [International Phone Support page](https://login.gov/help/manage-your-account/international-phone-support/), made a quick attempt to fix it
| --- | --- |
| <img width="645" alt="Screenshot 2024-04-29 at 8 45 27 AM" src="https://github.com/GSA-TTS/identity-site/assets/458784/40fc5cc2-527b-425c-ac2a-8a7ff7d9af30"> | <img width="645" alt="Screenshot 2024-04-29 at 8 45 31 AM" src="https://github.com/GSA-TTS/identity-site/assets/458784/ecb575b6-69ee-4d7b-8da2-cebae2273ae6"> |
=> Fix visual bug, icons scrolling in front of sticky header

content/_policy/contact._en.md, content/_policy/contact._es.md
Based on discussion [here](https://github.com/GSA-TTS/identity-site/pull/1240#discussion_r1591262509), this PR removes the `"title"` attribute from the links. For accessibility purposes, [W3C](https://www.w3.org/TR/WCAG20-TECHS/H33.html) says:
> For each anchor element that has a title attribute, check that the title attribute together with the link text describes the purpose of the link.
The titles in this case are instructions to follow the link, which do not describe the purpose of the link.
=> Remove titles from links

content/_help/specific-agencies/trusted-traveler-programs._en.md, content/_help/specific-agencies/trusted-traveler-programs._es.md, content/_help/specific-agencies/trusted-traveler-programs._fr.md, content/_help/specific-agencies/trusted-traveler-programs._zh.md
This PR removes articles that are causing failures in the `external-link-check` pipeline.
=> Remove dead CBP links

_includes/language_picker.html, spec/support/matchers.rb
Updates language picker to render links with a `hreflang` attribute.
Documentation: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#hreflang
**Why?**
- As documented, this creates a hint at the target language of the linked resource, which could be used by the browser or a search engine
- It's more meaningful for the exception that was added to spec verifying language links matching the page language
Previous discussion: https://github.com/GSA-TTS/identity-site/pull/1286#discussion_r1657498153
1. Go to https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/aduth-hreflang/
2. Inspect links in language picker
3. Observe `hreflang` attribute matches locale of the target link
=> Use hreflang for language picker, spec exception

_data/zh/settings.yml
Update language picker on the brochure site to say `语言` instead of `中文 (简体)` when `中文 (简体)` is selected.
=> Update zh settings.yml

content/_help/specific-agencies/trusted-traveler-programs._en.md, content/_help/specific-agencies/trusted-traveler-programs._es.md, content/_help/specific-agencies/trusted-traveler-programs._fr.md, content/_help/specific-agencies/trusted-traveler-programs._zh.md
Removes a broken link to TTP help article for "Application Status".
Related Slack discussion: https://gsa-tts.slack.com/archives/C0NGESUN5/p1721390880566609
1. Go to https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/aduth-rm-ttp-app-status/help/specific-agencies/trusted-traveler-programs/
2. Verify that all links under "Please contact the Trusted Traveler Programs directly if you have questions regarding:" go to a valid article on the DHS website
=> Remove broken link to TTP Application Status article

content/_help/specific-agencies/trusted-traveler-programs._en.md, content/_help/specific-agencies/trusted-traveler-programs._es.md, content/_help/specific-agencies/trusted-traveler-programs._fr.md, content/_help/specific-agencies/trusted-traveler-programs._zh.md
Adds links back to the Trusted Traveler Program (TTP) help article.
These were originally added in #1257, but were removed over time (#1262, #1280, #1301) due to them becoming invalid links at the DHS website. After some back and forth, the help resources have been restored, and we can add the links back.
Related Slack discussion: https://gsa-tts.slack.com/archives/C0NGESUN5/p1721390880566609
The process for this (reflected in commit history):
1. Restore files from original commit: `git checkout da9cc19 -- content/_help/specific-agencies/trusted-traveler-programs.*`
2. Remove still-invalid link for "Application changes" (this appears to have been rolled into content of "Application status")
3. Update link IDs, since they appear to have changed from the original
1. Go to …
=> Restore links to Trusted Traveler Program help article

_includes/components/post-office-search.html, assets/js/post_office_search.tsx
Following the changes in https://github.com/18F/identity-idp/pull/10940, we are more consistent in supporting localized search results. This PR adds the `locale` parameter so that results are translated appropriately.
| ![image](https://github.com/user-attachments/assets/6a541171-f8ab-4aa5-bd1b-368ea00ae91f) | ![image](https://github.com/user-attachments/assets/650db1c7-fd82-47d7-a95e-1433558cc5c5)   |
=> Pass locale parameter in USPS Post Office search to get localized results

content/_help/verify-your-identity/accepted-identification-documents._en.md, content/_help/verify-your-identity/accepted-identification-documents._es.md, content/_help/verify-your-identity/accepted-identification-documents._fr.md, content/_help/verify-your-identity/accepted-identification-documents._zh.md
[LG-13945](https://cm-jira.usa.gov/browse/LG-13945)
Added a redirect for `/help/verify-your-identity/accepted-state-issued-identification` back; it was mistakenly removed.
=> Added redirect back that shouldn't have been removed.

content/_help/trouble-signing-in/issues-with-authentication-methods._fr.md, content/_policy/accessibility._fr.md, spec/all_pages_spec.rb
Fixes a couple instances of invalid Markdown producing pages with lingering Markdown formatting.
Review the following pages and verify no broken Markdown:
- https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/aduth-broken-markdown-links/fr/help/trouble-signing-in/issues-with-authentication-methods/
- https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/aduth-broken-markdown-links/fr/accessibility/
Page|Before|After
---|---|---
Issues with authentication methods|![image](https://github.com/user-attachments/assets/ff34e824-fc12-4def-ac8c-386d744b3934)|![image](https://github.com/user-attachments/assets/c267e84a-188a-40b7-9663-f95a0eb4f4d8) …
=> Fix broken Markdown links for French content

_config.yml, _includes/search.html, spec/config_spec.rb, spec/data_spec.rb, spec/spec_helper.rb
[LG-9522](https://cm-jira.usa.gov/browse/LG-9522)
Currently, we only use the "login.gov" Search.gov affiliate. This is the English affiliate, but we should switch to the relevant one for the current language based on the selected language.
=> Add configuration for Search.gov affiliates for non-English languages (LG-9522)

_data/en/settings.yml, _data/es/settings.yml, _data/fr/settings.yml, _data/zh/settings.yml, _includes/sign_in.html
[LG-14155](https://cm-jira.usa.gov/browse/LG-14155)
Implements a simple solution to rearrange the ordering of Chinese text on a "sign in" button. 
- Updates the ordering of Chinese text for the "sign in" button at the top righthand corner of the page https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/LG-14155-update-chinese-translation/zh/
=> LG-14155: Update Chinese translation

_includes/contact_form.html, assets/js/populate_contact_form_agency.js, assets/js/query_params.js, spec/js/query_params_spec.js
[LG-14286](https://cm-jira.usa.gov/browse/LG-14286)
A staging instance can be found at:
- https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/LG-14286-expire-stale-parameters/contact/
Hit the URL with params to store the parameters for the form:
- https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/LG-14286-expire-stale-parameters/contact/?agency=agency1&integration=integration1
Refresh the page and notice that the params are stored in hidden values on the form.
Advance your computer's date 8+ days (if possible) and refresh the page. The parameters will now be cleared from localStorage and the hidden fields on the form.
=> LG-14286: Expire stale URL parameters (cache & flush values)

content/_help/verify-your-identity/phone-number._en.md, content/_help/verify-your-identity/phone-number._es.md, content/_help/verify-your-identity/phone-number._fr.md, content/_help/verify-your-identity/phone-number._zh.md
[LG-14223](https://cm-jira.usa.gov/browse/LG-14223)
Quoth the Jira:
> As a Login.gov user, I want to see a help article that clearly shows me the phone numbers I can and cannot use to verify my identity and that matches the icon bullets on other help articles on the site, so that I can feel confident in the information.
It is also my (completely unimportant) opinion that these make the page look much better, as an aside.
[English](https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/mattw/LG-14223-verify-icons/help/verify-your-identity/phone-number/) &middot; [French](https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/mattw/LG-14223-verify-icons/fr/he …
=> LG-14223 | Use icon bullets on "Verify your phone number" page

webpack.config.js
Looks like `import.meta.dirname` was added in a point release in the Nodejs v20 series.
We are requiring "20" as a version, so some compatible versions won't work without this.
=> Don't use import.meta.dirname in webpack.config.js

_data/en/settings.yml, _data/es/settings.yml, _data/fr/settings.yml, _data/zh/settings.yml
Now that we have the translations for PSHB, we can add them to the agency dropdown.
In the future, it would be nice to be able to publish the English version first, and then follow up with the translations when they're ready.
[LG-14744](https://cm-jira.usa.gov/browse/LG-14744)
=> Add PSHB to agencies dropdown

content/_help/get-started/authentication-methods._en.md, content/_help/get-started/authentication-methods._es.md, content/_help/get-started/authentication-methods._fr.md, content/_help/get-started/authentication-methods._zh.md
Updates the URL for one of the listed TOTP applications, currently causing builds to fail due to a 301 redirect.
Verify build passes.
Verify that all links for example TOTP applications go to the expected destination.
Preview URL: https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/aduth-totp-link-redirect/help/get-started/authentication-methods/#authentication-application
=> Fix redirected link for TOTP application

.circleci/config.yml
Updates CircleCI configuration to take advantage of CircleCI official orb command helpers for managing installation of Node.js and Node.js/Ruby dependencies.
**Why?**
- The current setup procedure is rather unstable, particularly at downloading Node.js. It's hoped that CircleCI may have better built-in tolerances for this (version caching, retry, etc.)
- It greatly simplifies the code, and avoids sketchy `wget | bash` piping
- Brings into alignment with other CircleCI-based Login.gov projects, specifically [`identity-dev-docs`](https://github.com/GSA-TTS/identity-dev-docs/blob/main/.circleci/config.yml) (h/t @monfresh for introducing these changes in https://github.com/GSA-TTS/identity-dev-docs/pull/477)
Reference documentation:
- …
=> Use CircleCI orbs to install Node.js and Node/Ruby dependencies

content/_partners/faq._en.md
[LG-14909](https://cm-jira.usa.gov/browse/LG-14909)
Updates the page at:
- https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.sites.pages.cloud.gov/preview/gsa-tts/identity-site/LG-14909-update-partner-faq/partners/faq/
=> LG-14909: Update partner FAQ

README.md
There is not a ticket. I will create one upon upon request 
- I updated the README to remove a step that is no longer needed to obtain mock data. The feature flag was removed in idp, [PR #11370](https://github.com/18F/identity-idp/pull/11370). I noticed it today while testing [PR# 1391](https://github.com/GSA-TTS/identity-site/pull/1391)
|  ![Screenshot 2024-11-15 at 3 05 37 PM](https://github.com/user-attachments/assets/e4f74b11-3e10-4397-9137-f172d8f84063) | <img width="404" alt="Screenshot 2024-11-15 at 3 22 02 PM" src="https://github.com/user-attachments/assets/af9956b1-bcf6-4770-8729-553ef009c82b">  |
=> Update Steps in the README To Get USPS Mock Data

assets/js/post_office_search.tsx, content/_help/verify-your-identity/verify-your-identity-in-person/find-a-participating-post-office._en.md, content/_help/verify-your-identity/verify-your-identity-in-person/find-a-participating-post-office._es.md, content/_help/verify-your-identity/verify-your-identity-in-person/find-a-participating-post-office._fr.md, content/_help/verify-your-identity/verify-your-identity-in-person/find-a-participating-post-office._zh.md, package-lock.json, package.json
[11857](https://cm-jira.usa.gov/browse/LG-11857)
Utilized a new prop in the `FullAddressSearch` component to display a header on top of the post office search results
=> LG-11857: add header post office search results

.circleci/config.yml
Ignores URL failures for external link check to apps.microsoft.com and faq.ssa.gov domains.
These URLs are currently causing failures, despite working in the browser.
Also removes (replaces) ignored URL for Chinese-language secure.login.gov . This was presumably added prior to the launch of this language, which is now generally available.
Verify build passes.
=> Add Microsoft & SSA domains to external URL ignore

_includes/partners/header.html
Noticed that we're inconsistent with our capitalization of developers.login.gov during a presentation that was displaying the partner page today. This changes it to be consistent.
=> Fix capitalization of Developers.login.gov

.circleci/config.yml
This PR adds the kantarainitiative.org to the `--url-ignore` list
=> add kantara initiative to url ignore list
